'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace EmployeeService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="EmpInstance", [Namespace]:="http://schemas.datacontract.org/2004/07/Employee"),  _
     System.SerializableAttribute()>  _
    Partial Public Class EmpInstance
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ACDLoginField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ActiveField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DeptIDField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmailField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmpIDField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmpLevelField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FullNameFirstLastField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FullNameLastFirstField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private HireDateField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IcomsIDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IcomsUserIDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private InfoTypeListField() As EmployeeService.InfoTypeItem
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LegacyWOWIDField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LocationField As EmployeeService.LookupInstance
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NTLoginField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OrganizationField As EmployeeService.LookupInstance
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PayrollIDField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SupEmailField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SupEmpIDField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SupFNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SupLNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SupNTLoginField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SupNameFirstLastField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SupNameLastFirstField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TermDateField As System.Nullable(Of Date)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ValidEmployeeField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ACDLogin() As String
            Get
                Return Me.ACDLoginField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ACDLoginField, value) <> true) Then
                    Me.ACDLoginField = value
                    Me.RaisePropertyChanged("ACDLogin")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Active() As Boolean
            Get
                Return Me.ActiveField
            End Get
            Set
                If (Me.ActiveField.Equals(value) <> true) Then
                    Me.ActiveField = value
                    Me.RaisePropertyChanged("Active")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DeptID() As Integer
            Get
                Return Me.DeptIDField
            End Get
            Set
                If (Me.DeptIDField.Equals(value) <> true) Then
                    Me.DeptIDField = value
                    Me.RaisePropertyChanged("DeptID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Email() As String
            Get
                Return Me.EmailField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EmailField, value) <> true) Then
                    Me.EmailField = value
                    Me.RaisePropertyChanged("Email")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EmpID() As Integer
            Get
                Return Me.EmpIDField
            End Get
            Set
                If (Me.EmpIDField.Equals(value) <> true) Then
                    Me.EmpIDField = value
                    Me.RaisePropertyChanged("EmpID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EmpLevel() As Integer
            Get
                Return Me.EmpLevelField
            End Get
            Set
                If (Me.EmpLevelField.Equals(value) <> true) Then
                    Me.EmpLevelField = value
                    Me.RaisePropertyChanged("EmpLevel")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FName() As String
            Get
                Return Me.FNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FNameField, value) <> true) Then
                    Me.FNameField = value
                    Me.RaisePropertyChanged("FName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FullNameFirstLast() As String
            Get
                Return Me.FullNameFirstLastField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FullNameFirstLastField, value) <> true) Then
                    Me.FullNameFirstLastField = value
                    Me.RaisePropertyChanged("FullNameFirstLast")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FullNameLastFirst() As String
            Get
                Return Me.FullNameLastFirstField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FullNameLastFirstField, value) <> true) Then
                    Me.FullNameLastFirstField = value
                    Me.RaisePropertyChanged("FullNameLastFirst")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property HireDate() As Date
            Get
                Return Me.HireDateField
            End Get
            Set
                If (Me.HireDateField.Equals(value) <> true) Then
                    Me.HireDateField = value
                    Me.RaisePropertyChanged("HireDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IcomsID() As String
            Get
                Return Me.IcomsIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IcomsIDField, value) <> true) Then
                    Me.IcomsIDField = value
                    Me.RaisePropertyChanged("IcomsID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IcomsUserID() As String
            Get
                Return Me.IcomsUserIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IcomsUserIDField, value) <> true) Then
                    Me.IcomsUserIDField = value
                    Me.RaisePropertyChanged("IcomsUserID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property InfoTypeList() As EmployeeService.InfoTypeItem()
            Get
                Return Me.InfoTypeListField
            End Get
            Set
                If (Object.ReferenceEquals(Me.InfoTypeListField, value) <> true) Then
                    Me.InfoTypeListField = value
                    Me.RaisePropertyChanged("InfoTypeList")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property LName() As String
            Get
                Return Me.LNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LNameField, value) <> true) Then
                    Me.LNameField = value
                    Me.RaisePropertyChanged("LName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property LegacyWOWID() As Integer
            Get
                Return Me.LegacyWOWIDField
            End Get
            Set
                If (Me.LegacyWOWIDField.Equals(value) <> true) Then
                    Me.LegacyWOWIDField = value
                    Me.RaisePropertyChanged("LegacyWOWID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Location() As EmployeeService.LookupInstance
            Get
                Return Me.LocationField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LocationField, value) <> true) Then
                    Me.LocationField = value
                    Me.RaisePropertyChanged("Location")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NTLogin() As String
            Get
                Return Me.NTLoginField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NTLoginField, value) <> true) Then
                    Me.NTLoginField = value
                    Me.RaisePropertyChanged("NTLogin")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Organization() As EmployeeService.LookupInstance
            Get
                Return Me.OrganizationField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OrganizationField, value) <> true) Then
                    Me.OrganizationField = value
                    Me.RaisePropertyChanged("Organization")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PayrollID() As Integer
            Get
                Return Me.PayrollIDField
            End Get
            Set
                If (Me.PayrollIDField.Equals(value) <> true) Then
                    Me.PayrollIDField = value
                    Me.RaisePropertyChanged("PayrollID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SupEmail() As String
            Get
                Return Me.SupEmailField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SupEmailField, value) <> true) Then
                    Me.SupEmailField = value
                    Me.RaisePropertyChanged("SupEmail")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SupEmpID() As Integer
            Get
                Return Me.SupEmpIDField
            End Get
            Set
                If (Me.SupEmpIDField.Equals(value) <> true) Then
                    Me.SupEmpIDField = value
                    Me.RaisePropertyChanged("SupEmpID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SupFName() As String
            Get
                Return Me.SupFNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SupFNameField, value) <> true) Then
                    Me.SupFNameField = value
                    Me.RaisePropertyChanged("SupFName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SupLName() As String
            Get
                Return Me.SupLNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SupLNameField, value) <> true) Then
                    Me.SupLNameField = value
                    Me.RaisePropertyChanged("SupLName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SupNTLogin() As String
            Get
                Return Me.SupNTLoginField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SupNTLoginField, value) <> true) Then
                    Me.SupNTLoginField = value
                    Me.RaisePropertyChanged("SupNTLogin")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SupNameFirstLast() As String
            Get
                Return Me.SupNameFirstLastField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SupNameFirstLastField, value) <> true) Then
                    Me.SupNameFirstLastField = value
                    Me.RaisePropertyChanged("SupNameFirstLast")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SupNameLastFirst() As String
            Get
                Return Me.SupNameLastFirstField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SupNameLastFirstField, value) <> true) Then
                    Me.SupNameLastFirstField = value
                    Me.RaisePropertyChanged("SupNameLastFirst")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TermDate() As System.Nullable(Of Date)
            Get
                Return Me.TermDateField
            End Get
            Set
                If (Me.TermDateField.Equals(value) <> true) Then
                    Me.TermDateField = value
                    Me.RaisePropertyChanged("TermDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ValidEmployee() As Boolean
            Get
                Return Me.ValidEmployeeField
            End Get
            Set
                If (Me.ValidEmployeeField.Equals(value) <> true) Then
                    Me.ValidEmployeeField = value
                    Me.RaisePropertyChanged("ValidEmployee")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="LookupInstance", [Namespace]:="http://schemas.datacontract.org/2004/07/Employee"),  _
     System.SerializableAttribute()>  _
    Partial Public Class LookupInstance
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DetailTextField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TextField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ValueField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DetailText() As String
            Get
                Return Me.DetailTextField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DetailTextField, value) <> true) Then
                    Me.DetailTextField = value
                    Me.RaisePropertyChanged("DetailText")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Text() As String
            Get
                Return Me.TextField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TextField, value) <> true) Then
                    Me.TextField = value
                    Me.RaisePropertyChanged("Text")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Value() As Integer
            Get
                Return Me.ValueField
            End Get
            Set
                If (Me.ValueField.Equals(value) <> true) Then
                    Me.ValueField = value
                    Me.RaisePropertyChanged("Value")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="InfoTypeItem", [Namespace]:="http://schemas.datacontract.org/2004/07/Employee"),  _
     System.SerializableAttribute()>  _
    Partial Public Class InfoTypeItem
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EnabledField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PrivateField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TypeIDField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TypeNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ValueField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ValueDataTypeField As EmployeeService.LookupInstance
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Enabled() As Boolean
            Get
                Return Me.EnabledField
            End Get
            Set
                If (Me.EnabledField.Equals(value) <> true) Then
                    Me.EnabledField = value
                    Me.RaisePropertyChanged("Enabled")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property [Private]() As Boolean
            Get
                Return Me.PrivateField
            End Get
            Set
                If (Me.PrivateField.Equals(value) <> true) Then
                    Me.PrivateField = value
                    Me.RaisePropertyChanged("Private")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TypeID() As Integer
            Get
                Return Me.TypeIDField
            End Get
            Set
                If (Me.TypeIDField.Equals(value) <> true) Then
                    Me.TypeIDField = value
                    Me.RaisePropertyChanged("TypeID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TypeName() As String
            Get
                Return Me.TypeNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TypeNameField, value) <> true) Then
                    Me.TypeNameField = value
                    Me.RaisePropertyChanged("TypeName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Value() As String
            Get
                Return Me.ValueField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ValueField, value) <> true) Then
                    Me.ValueField = value
                    Me.RaisePropertyChanged("Value")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ValueDataType() As EmployeeService.LookupInstance
            Get
                Return Me.ValueDataTypeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ValueDataTypeField, value) <> true) Then
                    Me.ValueDataTypeField = value
                    Me.RaisePropertyChanged("ValueDataType")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="HandledServiceFault", [Namespace]:="http://schemas.datacontract.org/2004/07/Employee"),  _
     System.SerializableAttribute()>  _
    Partial Public Class HandledServiceFault
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ArgsField As System.Collections.Generic.Dictionary(Of String, String)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MessageField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Args() As System.Collections.Generic.Dictionary(Of String, String)
            Get
                Return Me.ArgsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ArgsField, value) <> true) Then
                    Me.ArgsField = value
                    Me.RaisePropertyChanged("Args")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Message() As String
            Get
                Return Me.MessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MessageField, value) <> true) Then
                    Me.MessageField = value
                    Me.RaisePropertyChanged("Message")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="UnhandledServiceFault", [Namespace]:="http://schemas.datacontract.org/2004/07/Employee"),  _
     System.SerializableAttribute()>  _
    Partial Public Class UnhandledServiceFault
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MessageField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StackTraceField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Message() As String
            Get
                Return Me.MessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MessageField, value) <> true) Then
                    Me.MessageField = value
                    Me.RaisePropertyChanged("Message")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StackTrace() As String
            Get
                Return Me.StackTraceField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StackTraceField, value) <> true) Then
                    Me.StackTraceField = value
                    Me.RaisePropertyChanged("StackTrace")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="EmployeeService.IManagement")>  _
    Public Interface IManagement
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IManagement/GetBasicInfoByEmpID", ReplyAction:="http://tempuri.org/IManagement/GetBasicInfoByEmpIDResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(EmployeeService.HandledServiceFault), Action:="http://tempuri.org/IManagement/GetBasicInfoByEmpIDHandledServiceFaultFault", Name:="HandledServiceFault", [Namespace]:="http://schemas.datacontract.org/2004/07/Employee"),  _
         System.ServiceModel.FaultContractAttribute(GetType(EmployeeService.UnhandledServiceFault), Action:="http://tempuri.org/IManagement/GetBasicInfoByEmpIDUnhandledServiceFaultFault", Name:="UnhandledServiceFault", [Namespace]:="http://schemas.datacontract.org/2004/07/Employee")>  _
        Function GetBasicInfoByEmpID(ByVal empID As Integer) As EmployeeService.EmpInstance
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IManagement/GetBasicInfoByICOMSUserID", ReplyAction:="http://tempuri.org/IManagement/GetBasicInfoByICOMSUserIDResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(EmployeeService.HandledServiceFault), Action:="http://tempuri.org/IManagement/GetBasicInfoByICOMSUserIDHandledServiceFaultFault", Name:="HandledServiceFault", [Namespace]:="http://schemas.datacontract.org/2004/07/Employee"),  _
         System.ServiceModel.FaultContractAttribute(GetType(EmployeeService.UnhandledServiceFault), Action:="http://tempuri.org/IManagement/GetBasicInfoByICOMSUserIDUnhandledServiceFaultFaul"& _ 
            "t", Name:="UnhandledServiceFault", [Namespace]:="http://schemas.datacontract.org/2004/07/Employee")>  _
        Function GetBasicInfoByICOMSUserID(ByVal ICOMSUserID As String) As EmployeeService.EmpInstance
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IManagement/GetBasicInfoByICOMSSalesID", ReplyAction:="http://tempuri.org/IManagement/GetBasicInfoByICOMSSalesIDResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(EmployeeService.HandledServiceFault), Action:="http://tempuri.org/IManagement/GetBasicInfoByICOMSSalesIDHandledServiceFaultFault"& _ 
            "", Name:="HandledServiceFault", [Namespace]:="http://schemas.datacontract.org/2004/07/Employee"),  _
         System.ServiceModel.FaultContractAttribute(GetType(EmployeeService.UnhandledServiceFault), Action:="http://tempuri.org/IManagement/GetBasicInfoByICOMSSalesIDUnhandledServiceFaultFau"& _ 
            "lt", Name:="UnhandledServiceFault", [Namespace]:="http://schemas.datacontract.org/2004/07/Employee")>  _
        Function GetBasicInfoByICOMSSalesID(ByVal ICOMSSalesID As String) As EmployeeService.EmpInstance
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IManagement/GetBasicInfoByNTLogin", ReplyAction:="http://tempuri.org/IManagement/GetBasicInfoByNTLoginResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(EmployeeService.UnhandledServiceFault), Action:="http://tempuri.org/IManagement/GetBasicInfoByNTLoginUnhandledServiceFaultFault", Name:="UnhandledServiceFault", [Namespace]:="http://schemas.datacontract.org/2004/07/Employee"),  _
         System.ServiceModel.FaultContractAttribute(GetType(EmployeeService.HandledServiceFault), Action:="http://tempuri.org/IManagement/GetBasicInfoByNTLoginHandledServiceFaultFault", Name:="HandledServiceFault", [Namespace]:="http://schemas.datacontract.org/2004/07/Employee")>  _
        Function GetBasicInfoByNTLogin(ByVal NTLogin As String) As EmployeeService.EmpInstance
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IManagement/GetBasicInfoByInfoValue", ReplyAction:="http://tempuri.org/IManagement/GetBasicInfoByInfoValueResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(EmployeeService.HandledServiceFault), Action:="http://tempuri.org/IManagement/GetBasicInfoByInfoValueHandledServiceFaultFault", Name:="HandledServiceFault", [Namespace]:="http://schemas.datacontract.org/2004/07/Employee"),  _
         System.ServiceModel.FaultContractAttribute(GetType(EmployeeService.UnhandledServiceFault), Action:="http://tempuri.org/IManagement/GetBasicInfoByInfoValueUnhandledServiceFaultFault", Name:="UnhandledServiceFault", [Namespace]:="http://schemas.datacontract.org/2004/07/Employee")>  _
        Function GetBasicInfoByInfoValue(ByVal InfoValue As String, ByVal InfoTypeID As Integer) As EmployeeService.EmpInstance
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IManagement/GetAdvancedInfoByEmpID", ReplyAction:="http://tempuri.org/IManagement/GetAdvancedInfoByEmpIDResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(EmployeeService.UnhandledServiceFault), Action:="http://tempuri.org/IManagement/GetAdvancedInfoByEmpIDUnhandledServiceFaultFault", Name:="UnhandledServiceFault", [Namespace]:="http://schemas.datacontract.org/2004/07/Employee"),  _
         System.ServiceModel.FaultContractAttribute(GetType(EmployeeService.HandledServiceFault), Action:="http://tempuri.org/IManagement/GetAdvancedInfoByEmpIDHandledServiceFaultFault", Name:="HandledServiceFault", [Namespace]:="http://schemas.datacontract.org/2004/07/Employee")>  _
        Function GetAdvancedInfoByEmpID(ByVal empID As Integer) As EmployeeService.EmpInstance
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IManagement/GetAdvancedInfoByICOMSUserID", ReplyAction:="http://tempuri.org/IManagement/GetAdvancedInfoByICOMSUserIDResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(EmployeeService.UnhandledServiceFault), Action:="http://tempuri.org/IManagement/GetAdvancedInfoByICOMSUserIDUnhandledServiceFaultF"& _ 
            "ault", Name:="UnhandledServiceFault", [Namespace]:="http://schemas.datacontract.org/2004/07/Employee"),  _
         System.ServiceModel.FaultContractAttribute(GetType(EmployeeService.HandledServiceFault), Action:="http://tempuri.org/IManagement/GetAdvancedInfoByICOMSUserIDHandledServiceFaultFau"& _ 
            "lt", Name:="HandledServiceFault", [Namespace]:="http://schemas.datacontract.org/2004/07/Employee")>  _
        Function GetAdvancedInfoByICOMSUserID(ByVal ICOMSUserID As String) As EmployeeService.EmpInstance
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IManagement/GetAdvancedInfoByICOMSSalesID", ReplyAction:="http://tempuri.org/IManagement/GetAdvancedInfoByICOMSSalesIDResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(EmployeeService.UnhandledServiceFault), Action:="http://tempuri.org/IManagement/GetAdvancedInfoByICOMSSalesIDUnhandledServiceFault"& _ 
            "Fault", Name:="UnhandledServiceFault", [Namespace]:="http://schemas.datacontract.org/2004/07/Employee"),  _
         System.ServiceModel.FaultContractAttribute(GetType(EmployeeService.HandledServiceFault), Action:="http://tempuri.org/IManagement/GetAdvancedInfoByICOMSSalesIDHandledServiceFaultFa"& _ 
            "ult", Name:="HandledServiceFault", [Namespace]:="http://schemas.datacontract.org/2004/07/Employee")>  _
        Function GetAdvancedInfoByICOMSSalesID(ByVal ICOMSSalesID As String) As EmployeeService.EmpInstance
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IManagement/GetAdvancedInfoByNTLogin", ReplyAction:="http://tempuri.org/IManagement/GetAdvancedInfoByNTLoginResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(EmployeeService.UnhandledServiceFault), Action:="http://tempuri.org/IManagement/GetAdvancedInfoByNTLoginUnhandledServiceFaultFault"& _ 
            "", Name:="UnhandledServiceFault", [Namespace]:="http://schemas.datacontract.org/2004/07/Employee"),  _
         System.ServiceModel.FaultContractAttribute(GetType(EmployeeService.HandledServiceFault), Action:="http://tempuri.org/IManagement/GetAdvancedInfoByNTLoginHandledServiceFaultFault", Name:="HandledServiceFault", [Namespace]:="http://schemas.datacontract.org/2004/07/Employee")>  _
        Function GetAdvancedInfoByNTLogin(ByVal NTLogin As String) As EmployeeService.EmpInstance
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IManagement/GetAdvancedInfoByInfoValue", ReplyAction:="http://tempuri.org/IManagement/GetAdvancedInfoByInfoValueResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(EmployeeService.UnhandledServiceFault), Action:="http://tempuri.org/IManagement/GetAdvancedInfoByInfoValueUnhandledServiceFaultFau"& _ 
            "lt", Name:="UnhandledServiceFault", [Namespace]:="http://schemas.datacontract.org/2004/07/Employee"),  _
         System.ServiceModel.FaultContractAttribute(GetType(EmployeeService.HandledServiceFault), Action:="http://tempuri.org/IManagement/GetAdvancedInfoByInfoValueHandledServiceFaultFault"& _ 
            "", Name:="HandledServiceFault", [Namespace]:="http://schemas.datacontract.org/2004/07/Employee")>  _
        Function GetAdvancedInfoByInfoValue(ByVal InfoValue As String, ByVal InfoTypeID As Integer) As EmployeeService.EmpInstance
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IManagement/GetFullInfoByEmpID", ReplyAction:="http://tempuri.org/IManagement/GetFullInfoByEmpIDResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(EmployeeService.HandledServiceFault), Action:="http://tempuri.org/IManagement/GetFullInfoByEmpIDHandledServiceFaultFault", Name:="HandledServiceFault", [Namespace]:="http://schemas.datacontract.org/2004/07/Employee"),  _
         System.ServiceModel.FaultContractAttribute(GetType(EmployeeService.UnhandledServiceFault), Action:="http://tempuri.org/IManagement/GetFullInfoByEmpIDUnhandledServiceFaultFault", Name:="UnhandledServiceFault", [Namespace]:="http://schemas.datacontract.org/2004/07/Employee")>  _
        Function GetFullInfoByEmpID(ByVal empID As Integer) As EmployeeService.EmpInstance
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IManagement/GetFullInfoByICOMSUserID", ReplyAction:="http://tempuri.org/IManagement/GetFullInfoByICOMSUserIDResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(EmployeeService.HandledServiceFault), Action:="http://tempuri.org/IManagement/GetFullInfoByICOMSUserIDHandledServiceFaultFault", Name:="HandledServiceFault", [Namespace]:="http://schemas.datacontract.org/2004/07/Employee"),  _
         System.ServiceModel.FaultContractAttribute(GetType(EmployeeService.UnhandledServiceFault), Action:="http://tempuri.org/IManagement/GetFullInfoByICOMSUserIDUnhandledServiceFaultFault"& _ 
            "", Name:="UnhandledServiceFault", [Namespace]:="http://schemas.datacontract.org/2004/07/Employee")>  _
        Function GetFullInfoByICOMSUserID(ByVal ICOMSUserID As String) As EmployeeService.EmpInstance
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IManagement/GetFullInfoByICOMSSalesID", ReplyAction:="http://tempuri.org/IManagement/GetFullInfoByICOMSSalesIDResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(EmployeeService.HandledServiceFault), Action:="http://tempuri.org/IManagement/GetFullInfoByICOMSSalesIDHandledServiceFaultFault", Name:="HandledServiceFault", [Namespace]:="http://schemas.datacontract.org/2004/07/Employee"),  _
         System.ServiceModel.FaultContractAttribute(GetType(EmployeeService.UnhandledServiceFault), Action:="http://tempuri.org/IManagement/GetFullInfoByICOMSSalesIDUnhandledServiceFaultFaul"& _ 
            "t", Name:="UnhandledServiceFault", [Namespace]:="http://schemas.datacontract.org/2004/07/Employee")>  _
        Function GetFullInfoByICOMSSalesID(ByVal ICOMSSalesID As String) As EmployeeService.EmpInstance
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IManagement/GetFullInfoByNTLogin", ReplyAction:="http://tempuri.org/IManagement/GetFullInfoByNTLoginResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(EmployeeService.UnhandledServiceFault), Action:="http://tempuri.org/IManagement/GetFullInfoByNTLoginUnhandledServiceFaultFault", Name:="UnhandledServiceFault", [Namespace]:="http://schemas.datacontract.org/2004/07/Employee"),  _
         System.ServiceModel.FaultContractAttribute(GetType(EmployeeService.HandledServiceFault), Action:="http://tempuri.org/IManagement/GetFullInfoByNTLoginHandledServiceFaultFault", Name:="HandledServiceFault", [Namespace]:="http://schemas.datacontract.org/2004/07/Employee")>  _
        Function GetFullInfoByNTLogin(ByVal NTLogin As String) As EmployeeService.EmpInstance
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IManagement/GetFullInfoByInfoValue", ReplyAction:="http://tempuri.org/IManagement/GetFullInfoByInfoValueResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(EmployeeService.HandledServiceFault), Action:="http://tempuri.org/IManagement/GetFullInfoByInfoValueHandledServiceFaultFault", Name:="HandledServiceFault", [Namespace]:="http://schemas.datacontract.org/2004/07/Employee"),  _
         System.ServiceModel.FaultContractAttribute(GetType(EmployeeService.UnhandledServiceFault), Action:="http://tempuri.org/IManagement/GetFullInfoByInfoValueUnhandledServiceFaultFault", Name:="UnhandledServiceFault", [Namespace]:="http://schemas.datacontract.org/2004/07/Employee")>  _
        Function GetFullInfoByInfoValue(ByVal InfoValue As String, ByVal InfoTypeID As Integer) As EmployeeService.EmpInstance
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IManagement/BuildHierarchy", ReplyAction:="http://tempuri.org/IManagement/BuildHierarchyResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(EmployeeService.HandledServiceFault), Action:="http://tempuri.org/IManagement/BuildHierarchyHandledServiceFaultFault", Name:="HandledServiceFault", [Namespace]:="http://schemas.datacontract.org/2004/07/Employee"),  _
         System.ServiceModel.FaultContractAttribute(GetType(EmployeeService.UnhandledServiceFault), Action:="http://tempuri.org/IManagement/BuildHierarchyUnhandledServiceFaultFault", Name:="UnhandledServiceFault", [Namespace]:="http://schemas.datacontract.org/2004/07/Employee")>  _
        Sub BuildHierarchy()
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IManagementChannel
        Inherits EmployeeService.IManagement, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ManagementClient
        Inherits System.ServiceModel.ClientBase(Of EmployeeService.IManagement)
        Implements EmployeeService.IManagement
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetBasicInfoByEmpID(ByVal empID As Integer) As EmployeeService.EmpInstance Implements EmployeeService.IManagement.GetBasicInfoByEmpID
            Return MyBase.Channel.GetBasicInfoByEmpID(empID)
        End Function
        
        Public Function GetBasicInfoByICOMSUserID(ByVal ICOMSUserID As String) As EmployeeService.EmpInstance Implements EmployeeService.IManagement.GetBasicInfoByICOMSUserID
            Return MyBase.Channel.GetBasicInfoByICOMSUserID(ICOMSUserID)
        End Function
        
        Public Function GetBasicInfoByICOMSSalesID(ByVal ICOMSSalesID As String) As EmployeeService.EmpInstance Implements EmployeeService.IManagement.GetBasicInfoByICOMSSalesID
            Return MyBase.Channel.GetBasicInfoByICOMSSalesID(ICOMSSalesID)
        End Function
        
        Public Function GetBasicInfoByNTLogin(ByVal NTLogin As String) As EmployeeService.EmpInstance Implements EmployeeService.IManagement.GetBasicInfoByNTLogin
            Return MyBase.Channel.GetBasicInfoByNTLogin(NTLogin)
        End Function
        
        Public Function GetBasicInfoByInfoValue(ByVal InfoValue As String, ByVal InfoTypeID As Integer) As EmployeeService.EmpInstance Implements EmployeeService.IManagement.GetBasicInfoByInfoValue
            Return MyBase.Channel.GetBasicInfoByInfoValue(InfoValue, InfoTypeID)
        End Function
        
        Public Function GetAdvancedInfoByEmpID(ByVal empID As Integer) As EmployeeService.EmpInstance Implements EmployeeService.IManagement.GetAdvancedInfoByEmpID
            Return MyBase.Channel.GetAdvancedInfoByEmpID(empID)
        End Function
        
        Public Function GetAdvancedInfoByICOMSUserID(ByVal ICOMSUserID As String) As EmployeeService.EmpInstance Implements EmployeeService.IManagement.GetAdvancedInfoByICOMSUserID
            Return MyBase.Channel.GetAdvancedInfoByICOMSUserID(ICOMSUserID)
        End Function
        
        Public Function GetAdvancedInfoByICOMSSalesID(ByVal ICOMSSalesID As String) As EmployeeService.EmpInstance Implements EmployeeService.IManagement.GetAdvancedInfoByICOMSSalesID
            Return MyBase.Channel.GetAdvancedInfoByICOMSSalesID(ICOMSSalesID)
        End Function
        
        Public Function GetAdvancedInfoByNTLogin(ByVal NTLogin As String) As EmployeeService.EmpInstance Implements EmployeeService.IManagement.GetAdvancedInfoByNTLogin
            Return MyBase.Channel.GetAdvancedInfoByNTLogin(NTLogin)
        End Function
        
        Public Function GetAdvancedInfoByInfoValue(ByVal InfoValue As String, ByVal InfoTypeID As Integer) As EmployeeService.EmpInstance Implements EmployeeService.IManagement.GetAdvancedInfoByInfoValue
            Return MyBase.Channel.GetAdvancedInfoByInfoValue(InfoValue, InfoTypeID)
        End Function
        
        Public Function GetFullInfoByEmpID(ByVal empID As Integer) As EmployeeService.EmpInstance Implements EmployeeService.IManagement.GetFullInfoByEmpID
            Return MyBase.Channel.GetFullInfoByEmpID(empID)
        End Function
        
        Public Function GetFullInfoByICOMSUserID(ByVal ICOMSUserID As String) As EmployeeService.EmpInstance Implements EmployeeService.IManagement.GetFullInfoByICOMSUserID
            Return MyBase.Channel.GetFullInfoByICOMSUserID(ICOMSUserID)
        End Function
        
        Public Function GetFullInfoByICOMSSalesID(ByVal ICOMSSalesID As String) As EmployeeService.EmpInstance Implements EmployeeService.IManagement.GetFullInfoByICOMSSalesID
            Return MyBase.Channel.GetFullInfoByICOMSSalesID(ICOMSSalesID)
        End Function
        
        Public Function GetFullInfoByNTLogin(ByVal NTLogin As String) As EmployeeService.EmpInstance Implements EmployeeService.IManagement.GetFullInfoByNTLogin
            Return MyBase.Channel.GetFullInfoByNTLogin(NTLogin)
        End Function
        
        Public Function GetFullInfoByInfoValue(ByVal InfoValue As String, ByVal InfoTypeID As Integer) As EmployeeService.EmpInstance Implements EmployeeService.IManagement.GetFullInfoByInfoValue
            Return MyBase.Channel.GetFullInfoByInfoValue(InfoValue, InfoTypeID)
        End Function
        
        Public Sub BuildHierarchy() Implements EmployeeService.IManagement.BuildHierarchy
            MyBase.Channel.BuildHierarchy
        End Sub
    End Class
End Namespace
