'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18034
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace EmailService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="EmailMessage", [Namespace]:="http://schemas.datacontract.org/2004/07/Email"),  _
     System.SerializableAttribute()>  _
    Partial Public Class EmailMessage
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BCCField() As String
        
        Private BodyField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CCField() As String
        
        Private FromField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IsBodyHtmlField As Boolean
        
        Private PriorityField As EmailService.MailPriority
        
        Private SubjectField As String
        
        Private ToField() As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BCC() As String()
            Get
                Return Me.BCCField
            End Get
            Set
                If (Object.ReferenceEquals(Me.BCCField, value) <> true) Then
                    Me.BCCField = value
                    Me.RaisePropertyChanged("BCC")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Body() As String
            Get
                Return Me.BodyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.BodyField, value) <> true) Then
                    Me.BodyField = value
                    Me.RaisePropertyChanged("Body")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CC() As String()
            Get
                Return Me.CCField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CCField, value) <> true) Then
                    Me.CCField = value
                    Me.RaisePropertyChanged("CC")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property From() As String
            Get
                Return Me.FromField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FromField, value) <> true) Then
                    Me.FromField = value
                    Me.RaisePropertyChanged("From")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IsBodyHtml() As Boolean
            Get
                Return Me.IsBodyHtmlField
            End Get
            Set
                If (Me.IsBodyHtmlField.Equals(value) <> true) Then
                    Me.IsBodyHtmlField = value
                    Me.RaisePropertyChanged("IsBodyHtml")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Priority() As EmailService.MailPriority
            Get
                Return Me.PriorityField
            End Get
            Set
                If (Me.PriorityField.Equals(value) <> true) Then
                    Me.PriorityField = value
                    Me.RaisePropertyChanged("Priority")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Subject() As String
            Get
                Return Me.SubjectField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SubjectField, value) <> true) Then
                    Me.SubjectField = value
                    Me.RaisePropertyChanged("Subject")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property [To]() As String()
            Get
                Return Me.ToField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ToField, value) <> true) Then
                    Me.ToField = value
                    Me.RaisePropertyChanged("To")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="MailPriority", [Namespace]:="http://schemas.datacontract.org/2004/07/Email")>  _
    Public Enum MailPriority As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Normal = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Low = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        High = 2
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="UnhandledServiceFault", [Namespace]:="http://schemas.datacontract.org/2004/07/Email"),  _
     System.SerializableAttribute()>  _
    Partial Public Class UnhandledServiceFault
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MessageField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StackTraceField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Message() As String
            Get
                Return Me.MessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MessageField, value) <> true) Then
                    Me.MessageField = value
                    Me.RaisePropertyChanged("Message")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StackTrace() As String
            Get
                Return Me.StackTraceField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StackTraceField, value) <> true) Then
                    Me.StackTraceField = value
                    Me.RaisePropertyChanged("StackTrace")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="HandledServiceFault", [Namespace]:="http://schemas.datacontract.org/2004/07/Email"),  _
     System.SerializableAttribute()>  _
    Partial Public Class HandledServiceFault
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ArgsField As System.Collections.Generic.Dictionary(Of String, String)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MessageField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Args() As System.Collections.Generic.Dictionary(Of String, String)
            Get
                Return Me.ArgsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ArgsField, value) <> true) Then
                    Me.ArgsField = value
                    Me.RaisePropertyChanged("Args")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Message() As String
            Get
                Return Me.MessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MessageField, value) <> true) Then
                    Me.MessageField = value
                    Me.RaisePropertyChanged("Message")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="", ConfigurationName:="EmailService.IOperations")>  _
    Public Interface IOperations
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:IOperations/SendEmail", ReplyAction:="urn:IOperations/SendEmailResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(EmailService.UnhandledServiceFault), Action:="urn:IOperations/SendEmailUnhandledServiceFaultFault", Name:="UnhandledServiceFault", [Namespace]:="http://schemas.datacontract.org/2004/07/Email"),  _
         System.ServiceModel.FaultContractAttribute(GetType(EmailService.HandledServiceFault), Action:="urn:IOperations/SendEmailHandledServiceFaultFault", Name:="HandledServiceFault", [Namespace]:="http://schemas.datacontract.org/2004/07/Email")>  _
        Sub SendEmail(ByVal myEmailMessage As EmailService.EmailMessage)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IOperationsChannel
        Inherits EmailService.IOperations, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class OperationsClient
        Inherits System.ServiceModel.ClientBase(Of EmailService.IOperations)
        Implements EmailService.IOperations
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Sub SendEmail(ByVal myEmailMessage As EmailService.EmailMessage) Implements EmailService.IOperations.SendEmail
            MyBase.Channel.SendEmail(myEmailMessage)
        End Sub
    End Class
End Namespace
