'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace AddressService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="AddressBase", [Namespace]:="http://schemas.datacontract.org/2004/07/Address"),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(AddressService.AddressValidateOutput)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(AddressService.AddressIcoms))>  _
    Partial Public Class AddressBase
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Addr1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Addr2Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CityField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FormattedAddressField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private HouseNumberField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StateField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StreetNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ZipField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Zip4Field As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Addr1() As String
            Get
                Return Me.Addr1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Addr1Field, value) <> true) Then
                    Me.Addr1Field = value
                    Me.RaisePropertyChanged("Addr1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Addr2() As String
            Get
                Return Me.Addr2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Addr2Field, value) <> true) Then
                    Me.Addr2Field = value
                    Me.RaisePropertyChanged("Addr2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property City() As String
            Get
                Return Me.CityField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CityField, value) <> true) Then
                    Me.CityField = value
                    Me.RaisePropertyChanged("City")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FormattedAddress() As String
            Get
                Return Me.FormattedAddressField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FormattedAddressField, value) <> true) Then
                    Me.FormattedAddressField = value
                    Me.RaisePropertyChanged("FormattedAddress")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property HouseNumber() As String
            Get
                Return Me.HouseNumberField
            End Get
            Set
                If (Object.ReferenceEquals(Me.HouseNumberField, value) <> true) Then
                    Me.HouseNumberField = value
                    Me.RaisePropertyChanged("HouseNumber")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property State() As String
            Get
                Return Me.StateField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StateField, value) <> true) Then
                    Me.StateField = value
                    Me.RaisePropertyChanged("State")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StreetName() As String
            Get
                Return Me.StreetNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StreetNameField, value) <> true) Then
                    Me.StreetNameField = value
                    Me.RaisePropertyChanged("StreetName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Zip() As String
            Get
                Return Me.ZipField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ZipField, value) <> true) Then
                    Me.ZipField = value
                    Me.RaisePropertyChanged("Zip")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Zip4() As String
            Get
                Return Me.Zip4Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Zip4Field, value) <> true) Then
                    Me.Zip4Field = value
                    Me.RaisePropertyChanged("Zip4")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="AddressValidateOutput", [Namespace]:="http://schemas.datacontract.org/2004/07/Address"),  _
     System.SerializableAttribute()>  _
    Partial Public Class AddressValidateOutput
        Inherits AddressService.AddressBase
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AddressConfirmedField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DuoShareMessageField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FriendlyResultMessageField As String
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AddressConfirmed() As Boolean
            Get
                Return Me.AddressConfirmedField
            End Get
            Set
                If (Me.AddressConfirmedField.Equals(value) <> true) Then
                    Me.AddressConfirmedField = value
                    Me.RaisePropertyChanged("AddressConfirmed")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DuoShareMessage() As String
            Get
                Return Me.DuoShareMessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DuoShareMessageField, value) <> true) Then
                    Me.DuoShareMessageField = value
                    Me.RaisePropertyChanged("DuoShareMessage")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FriendlyResultMessage() As String
            Get
                Return Me.FriendlyResultMessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FriendlyResultMessageField, value) <> true) Then
                    Me.FriendlyResultMessageField = value
                    Me.RaisePropertyChanged("FriendlyResultMessage")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="AddressIcoms", [Namespace]:="http://schemas.datacontract.org/2004/07/Address"),  _
     System.SerializableAttribute()>  _
    Partial Public Class AddressIcoms
        Inherits AddressService.AddressBase
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CompanyField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DivisionField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FranchiseField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FranchiseNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IcomsLocationIDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LegacyPrinField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PoolField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ValidField As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Company() As Integer
            Get
                Return Me.CompanyField
            End Get
            Set
                If (Me.CompanyField.Equals(value) <> true) Then
                    Me.CompanyField = value
                    Me.RaisePropertyChanged("Company")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Division() As Integer
            Get
                Return Me.DivisionField
            End Get
            Set
                If (Me.DivisionField.Equals(value) <> true) Then
                    Me.DivisionField = value
                    Me.RaisePropertyChanged("Division")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Franchise() As Integer
            Get
                Return Me.FranchiseField
            End Get
            Set
                If (Me.FranchiseField.Equals(value) <> true) Then
                    Me.FranchiseField = value
                    Me.RaisePropertyChanged("Franchise")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FranchiseName() As String
            Get
                Return Me.FranchiseNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FranchiseNameField, value) <> true) Then
                    Me.FranchiseNameField = value
                    Me.RaisePropertyChanged("FranchiseName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IcomsLocationID() As String
            Get
                Return Me.IcomsLocationIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IcomsLocationIDField, value) <> true) Then
                    Me.IcomsLocationIDField = value
                    Me.RaisePropertyChanged("IcomsLocationID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property LegacyPrin() As String
            Get
                Return Me.LegacyPrinField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LegacyPrinField, value) <> true) Then
                    Me.LegacyPrinField = value
                    Me.RaisePropertyChanged("LegacyPrin")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Pool() As String
            Get
                Return Me.PoolField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PoolField, value) <> true) Then
                    Me.PoolField = value
                    Me.RaisePropertyChanged("Pool")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Valid() As Boolean
            Get
                Return Me.ValidField
            End Get
            Set
                If (Me.ValidField.Equals(value) <> true) Then
                    Me.ValidField = value
                    Me.RaisePropertyChanged("Valid")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="HandledServiceFault", [Namespace]:="http://schemas.datacontract.org/2004/07/Address"),  _
     System.SerializableAttribute()>  _
    Partial Public Class HandledServiceFault
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ArgsField As System.Collections.Generic.Dictionary(Of String, String)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MessageField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Args() As System.Collections.Generic.Dictionary(Of String, String)
            Get
                Return Me.ArgsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ArgsField, value) <> true) Then
                    Me.ArgsField = value
                    Me.RaisePropertyChanged("Args")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Message() As String
            Get
                Return Me.MessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MessageField, value) <> true) Then
                    Me.MessageField = value
                    Me.RaisePropertyChanged("Message")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="UnhandledServiceFault", [Namespace]:="http://schemas.datacontract.org/2004/07/Address"),  _
     System.SerializableAttribute()>  _
    Partial Public Class UnhandledServiceFault
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MessageField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StackTraceField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Message() As String
            Get
                Return Me.MessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MessageField, value) <> true) Then
                    Me.MessageField = value
                    Me.RaisePropertyChanged("Message")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StackTrace() As String
            Get
                Return Me.StackTraceField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StackTraceField, value) <> true) Then
                    Me.StackTraceField = value
                    Me.RaisePropertyChanged("StackTrace")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="AddressService.IAddressManagement")>  _
    Public Interface IAddressManagement
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IAddressManagement/getAddressByLocation", ReplyAction:="http://tempuri.org/IAddressManagement/getAddressByLocationResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(AddressService.HandledServiceFault), Action:="http://tempuri.org/IAddressManagement/getAddressByLocationHandledServiceFaultFaul"& _ 
            "t", Name:="HandledServiceFault", [Namespace]:="http://schemas.datacontract.org/2004/07/Address"),  _
         System.ServiceModel.FaultContractAttribute(GetType(AddressService.UnhandledServiceFault), Action:="http://tempuri.org/IAddressManagement/getAddressByLocationUnhandledServiceFaultFa"& _ 
            "ult", Name:="UnhandledServiceFault", [Namespace]:="http://schemas.datacontract.org/2004/07/Address")>  _
        Function getAddressByLocation(ByVal locationID As String) As AddressService.AddressIcoms
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IAddressManagement/validateAddress", ReplyAction:="http://tempuri.org/IAddressManagement/validateAddressResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(AddressService.HandledServiceFault), Action:="http://tempuri.org/IAddressManagement/validateAddressHandledServiceFaultFault", Name:="HandledServiceFault", [Namespace]:="http://schemas.datacontract.org/2004/07/Address"),  _
         System.ServiceModel.FaultContractAttribute(GetType(AddressService.UnhandledServiceFault), Action:="http://tempuri.org/IAddressManagement/validateAddressUnhandledServiceFaultFault", Name:="UnhandledServiceFault", [Namespace]:="http://schemas.datacontract.org/2004/07/Address")>  _
        Function validateAddress(ByVal inputAddress As AddressService.AddressBase) As AddressService.AddressValidateOutput
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IAddressManagement/buildAddress", ReplyAction:="http://tempuri.org/IAddressManagement/buildAddressResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(AddressService.HandledServiceFault), Action:="http://tempuri.org/IAddressManagement/buildAddressHandledServiceFaultFault", Name:="HandledServiceFault", [Namespace]:="http://schemas.datacontract.org/2004/07/Address"),  _
         System.ServiceModel.FaultContractAttribute(GetType(AddressService.UnhandledServiceFault), Action:="http://tempuri.org/IAddressManagement/buildAddressUnhandledServiceFaultFault", Name:="UnhandledServiceFault", [Namespace]:="http://schemas.datacontract.org/2004/07/Address")>  _
        Function buildAddress(ByVal inputAddress As AddressService.AddressBase) As AddressService.AddressBase
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IAddressManagement/getAddressByAddress", ReplyAction:="http://tempuri.org/IAddressManagement/getAddressByAddressResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(AddressService.HandledServiceFault), Action:="http://tempuri.org/IAddressManagement/getAddressByAddressHandledServiceFaultFault"& _ 
            "", Name:="HandledServiceFault", [Namespace]:="http://schemas.datacontract.org/2004/07/Address"),  _
         System.ServiceModel.FaultContractAttribute(GetType(AddressService.UnhandledServiceFault), Action:="http://tempuri.org/IAddressManagement/getAddressByAddressUnhandledServiceFaultFau"& _ 
            "lt", Name:="UnhandledServiceFault", [Namespace]:="http://schemas.datacontract.org/2004/07/Address")>  _
        Function getAddressByAddress(ByVal inputAddress As AddressService.AddressBase) As AddressService.AddressIcoms
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IAddressManagementChannel
        Inherits AddressService.IAddressManagement, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class AddressManagementClient
        Inherits System.ServiceModel.ClientBase(Of AddressService.IAddressManagement)
        Implements AddressService.IAddressManagement
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function getAddressByLocation(ByVal locationID As String) As AddressService.AddressIcoms Implements AddressService.IAddressManagement.getAddressByLocation
            Return MyBase.Channel.getAddressByLocation(locationID)
        End Function
        
        Public Function validateAddress(ByVal inputAddress As AddressService.AddressBase) As AddressService.AddressValidateOutput Implements AddressService.IAddressManagement.validateAddress
            Return MyBase.Channel.validateAddress(inputAddress)
        End Function
        
        Public Function buildAddress(ByVal inputAddress As AddressService.AddressBase) As AddressService.AddressBase Implements AddressService.IAddressManagement.buildAddress
            Return MyBase.Channel.buildAddress(inputAddress)
        End Function
        
        Public Function getAddressByAddress(ByVal inputAddress As AddressService.AddressBase) As AddressService.AddressIcoms Implements AddressService.IAddressManagement.getAddressByAddress
            Return MyBase.Channel.getAddressByAddress(inputAddress)
        End Function
    End Class
End Namespace
