
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("ed3472b5-6c3e-498f-b2df-6843dabf6018")>
#Region "EDM Relationship Metadata"
<Assembly: EdmRelationshipAttribute("ICOMSModel", "FK_Franchise_UPS_DivisionLookups_UPS", "DivisionLookups_UPS", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(DivisionLookups_UPS), "Franchise_UPS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Franchise_UPS), True)>

#End Region

#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class ICOMSEntities
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new ICOMSEntities object using the connection string found in the 'ICOMSEntities' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=ICOMSEntities", "ICOMSEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new ICOMSEntities object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "ICOMSEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new ICOMSEntities object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "ICOMSEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property DivisionLookups_UPS() As ObjectSet(Of DivisionLookups_UPS)
        Get
            If (_DivisionLookups_UPS Is Nothing) Then
                _DivisionLookups_UPS = MyBase.CreateObjectSet(Of DivisionLookups_UPS)("DivisionLookups_UPS")
            End If
            Return _DivisionLookups_UPS
        End Get
    End Property

    Private _DivisionLookups_UPS As ObjectSet(Of DivisionLookups_UPS)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Franchise_UPS() As ObjectSet(Of Franchise_UPS)
        Get
            If (_Franchise_UPS Is Nothing) Then
                _Franchise_UPS = MyBase.CreateObjectSet(Of Franchise_UPS)("Franchise_UPS")
            End If
            Return _Franchise_UPS
        End Get
    End Property

    Private _Franchise_UPS As ObjectSet(Of Franchise_UPS)

    #End Region

    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the DivisionLookups_UPS EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToDivisionLookups_UPS(ByVal divisionLookups_UPS As DivisionLookups_UPS)
        MyBase.AddObject("DivisionLookups_UPS", divisionLookups_UPS)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Franchise_UPS EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToFranchise_UPS(ByVal franchise_UPS As Franchise_UPS)
        MyBase.AddObject("Franchise_UPS", franchise_UPS)
    End Sub

    #End Region

End Class

#End Region

#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="ICOMSModel", Name:="DivisionLookups_UPS")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class DivisionLookups_UPS
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new DivisionLookups_UPS object.
    ''' </summary>
    ''' <param name="division">Initial value of the Division property.</param>
    ''' <param name="uPS_EmailAddress">Initial value of the UPS_EmailAddress property.</param>
    ''' <param name="timeZone">Initial value of the TimeZone property.</param>
    ''' <param name="state">Initial value of the State property.</param>
    ''' <param name="stateAbbr">Initial value of the StateAbbr property.</param>
    Public Shared Function CreateDivisionLookups_UPS(division As Global.System.Decimal, uPS_EmailAddress As Global.System.String, timeZone As Global.System.Int32, state As Global.System.String, stateAbbr As Global.System.String) As DivisionLookups_UPS
        Dim divisionLookups_UPS as DivisionLookups_UPS = New DivisionLookups_UPS
        divisionLookups_UPS.Division = division
        divisionLookups_UPS.UPS_EmailAddress = uPS_EmailAddress
        divisionLookups_UPS.TimeZone = timeZone
        divisionLookups_UPS.State = state
        divisionLookups_UPS.StateAbbr = stateAbbr
        Return divisionLookups_UPS
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Division() As Global.System.Decimal
        Get
            Return _Division
        End Get
        Set
            If (_Division <> Value) Then
                OnDivisionChanging(value)
                ReportPropertyChanging("Division")
                _Division = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Division")
                OnDivisionChanged()
            End If
        End Set
    End Property

    Private _Division As Global.System.Decimal
    Private Partial Sub OnDivisionChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnDivisionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property UPS_EmailAddress() As Global.System.String
        Get
            Return _UPS_EmailAddress
        End Get
        Set
            OnUPS_EmailAddressChanging(value)
            ReportPropertyChanging("UPS_EmailAddress")
            _UPS_EmailAddress = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("UPS_EmailAddress")
            OnUPS_EmailAddressChanged()
        End Set
    End Property

    Private _UPS_EmailAddress As Global.System.String
    Private Partial Sub OnUPS_EmailAddressChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnUPS_EmailAddressChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property TimeZone() As Global.System.Int32
        Get
            Return _TimeZone
        End Get
        Set
            OnTimeZoneChanging(value)
            ReportPropertyChanging("TimeZone")
            _TimeZone = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("TimeZone")
            OnTimeZoneChanged()
        End Set
    End Property

    Private _TimeZone As Global.System.Int32
    Private Partial Sub OnTimeZoneChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnTimeZoneChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property State() As Global.System.String
        Get
            Return _State
        End Get
        Set
            OnStateChanging(value)
            ReportPropertyChanging("State")
            _State = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("State")
            OnStateChanged()
        End Set
    End Property

    Private _State As Global.System.String
    Private Partial Sub OnStateChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnStateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property StateAbbr() As Global.System.String
        Get
            Return _StateAbbr
        End Get
        Set
            OnStateAbbrChanging(value)
            ReportPropertyChanging("StateAbbr")
            _StateAbbr = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("StateAbbr")
            OnStateAbbrChanged()
        End Set
    End Property

    Private _StateAbbr As Global.System.String
    Private Partial Sub OnStateAbbrChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnStateAbbrChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property DivisionName() As Global.System.String
        Get
            Return _DivisionName
        End Get
        Set
            OnDivisionNameChanging(value)
            ReportPropertyChanging("DivisionName")
            _DivisionName = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("DivisionName")
            OnDivisionNameChanged()
        End Set
    End Property

    Private _DivisionName As Global.System.String
    Private Partial Sub OnDivisionNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnDivisionNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property SYSPRIN() As Global.System.String
        Get
            Return _SYSPRIN
        End Get
        Set
            OnSYSPRINChanging(value)
            ReportPropertyChanging("SYSPRIN")
            _SYSPRIN = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("SYSPRIN")
            OnSYSPRINChanged()
        End Set
    End Property

    Private _SYSPRIN As Global.System.String
    Private Partial Sub OnSYSPRINChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnSYSPRINChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Agent() As Global.System.String
        Get
            Return _Agent
        End Get
        Set
            OnAgentChanging(value)
            ReportPropertyChanging("Agent")
            _Agent = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Agent")
            OnAgentChanged()
        End Set
    End Property

    Private _Agent As Global.System.String
    Private Partial Sub OnAgentChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnAgentChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Site() As Global.System.String
        Get
            Return _Site
        End Get
        Set
            OnSiteChanging(value)
            ReportPropertyChanging("Site")
            _Site = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Site")
            OnSiteChanged()
        End Set
    End Property

    Private _Site As Global.System.String
    Private Partial Sub OnSiteChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnSiteChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ICOMSModel", "FK_Franchise_UPS_DivisionLookups_UPS", "Franchise_UPS")>
     Public Property Franchise_UPS() As EntityCollection(Of Franchise_UPS)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Franchise_UPS)("ICOMSModel.FK_Franchise_UPS_DivisionLookups_UPS", "Franchise_UPS")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Franchise_UPS)("ICOMSModel.FK_Franchise_UPS_DivisionLookups_UPS", "Franchise_UPS", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="ICOMSModel", Name:="Franchise_UPS")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Franchise_UPS
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Franchise_UPS object.
    ''' </summary>
    ''' <param name="dBID">Initial value of the DBID property.</param>
    ''' <param name="franchise">Initial value of the Franchise property.</param>
    ''' <param name="franchiseName">Initial value of the FranchiseName property.</param>
    ''' <param name="division">Initial value of the Division property.</param>
    ''' <param name="divisionName">Initial value of the DivisionName property.</param>
    ''' <param name="company">Initial value of the Company property.</param>
    ''' <param name="site">Initial value of the Site property.</param>
    ''' <param name="state">Initial value of the State property.</param>
    ''' <param name="stateAbbr">Initial value of the StateAbbr property.</param>
    Public Shared Function CreateFranchise_UPS(dBID As Global.System.Int32, franchise As Global.System.String, franchiseName As Global.System.String, division As Global.System.Decimal, divisionName As Global.System.String, company As Global.System.String, site As Global.System.String, state As Global.System.String, stateAbbr As Global.System.String) As Franchise_UPS
        Dim franchise_UPS as Franchise_UPS = New Franchise_UPS
        franchise_UPS.DBID = dBID
        franchise_UPS.Franchise = franchise
        franchise_UPS.FranchiseName = franchiseName
        franchise_UPS.Division = division
        franchise_UPS.DivisionName = divisionName
        franchise_UPS.Company = company
        franchise_UPS.Site = site
        franchise_UPS.State = state
        franchise_UPS.StateAbbr = stateAbbr
        Return franchise_UPS
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property DBID() As Global.System.Int32
        Get
            Return _DBID
        End Get
        Set
            If (_DBID <> Value) Then
                OnDBIDChanging(value)
                ReportPropertyChanging("DBID")
                _DBID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("DBID")
                OnDBIDChanged()
            End If
        End Set
    End Property

    Private _DBID As Global.System.Int32
    Private Partial Sub OnDBIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnDBIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Franchise() As Global.System.String
        Get
            Return _Franchise
        End Get
        Set
            OnFranchiseChanging(value)
            ReportPropertyChanging("Franchise")
            _Franchise = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Franchise")
            OnFranchiseChanged()
        End Set
    End Property

    Private _Franchise As Global.System.String
    Private Partial Sub OnFranchiseChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnFranchiseChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property FranchiseName() As Global.System.String
        Get
            Return _FranchiseName
        End Get
        Set
            OnFranchiseNameChanging(value)
            ReportPropertyChanging("FranchiseName")
            _FranchiseName = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("FranchiseName")
            OnFranchiseNameChanged()
        End Set
    End Property

    Private _FranchiseName As Global.System.String
    Private Partial Sub OnFranchiseNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnFranchiseNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Division() As Global.System.Decimal
        Get
            Return _Division
        End Get
        Set
            OnDivisionChanging(value)
            ReportPropertyChanging("Division")
            _Division = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Division")
            OnDivisionChanged()
        End Set
    End Property

    Private _Division As Global.System.Decimal
    Private Partial Sub OnDivisionChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnDivisionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property DivisionName() As Global.System.String
        Get
            Return _DivisionName
        End Get
        Set
            OnDivisionNameChanging(value)
            ReportPropertyChanging("DivisionName")
            _DivisionName = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("DivisionName")
            OnDivisionNameChanged()
        End Set
    End Property

    Private _DivisionName As Global.System.String
    Private Partial Sub OnDivisionNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnDivisionNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Company() As Global.System.String
        Get
            Return _Company
        End Get
        Set
            OnCompanyChanging(value)
            ReportPropertyChanging("Company")
            _Company = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Company")
            OnCompanyChanged()
        End Set
    End Property

    Private _Company As Global.System.String
    Private Partial Sub OnCompanyChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCompanyChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Site() As Global.System.String
        Get
            Return _Site
        End Get
        Set
            OnSiteChanging(value)
            ReportPropertyChanging("Site")
            _Site = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Site")
            OnSiteChanged()
        End Set
    End Property

    Private _Site As Global.System.String
    Private Partial Sub OnSiteChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnSiteChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property SYSPRIN() As Global.System.String
        Get
            Return _SYSPRIN
        End Get
        Set
            OnSYSPRINChanging(value)
            ReportPropertyChanging("SYSPRIN")
            _SYSPRIN = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("SYSPRIN")
            OnSYSPRINChanged()
        End Set
    End Property

    Private _SYSPRIN As Global.System.String
    Private Partial Sub OnSYSPRINChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnSYSPRINChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Agent() As Global.System.String
        Get
            Return _Agent
        End Get
        Set
            OnAgentChanging(value)
            ReportPropertyChanging("Agent")
            _Agent = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Agent")
            OnAgentChanged()
        End Set
    End Property

    Private _Agent As Global.System.String
    Private Partial Sub OnAgentChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnAgentChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Timezone() As Nullable(Of Global.System.Int32)
        Get
            Return _Timezone
        End Get
        Set
            OnTimezoneChanging(value)
            ReportPropertyChanging("Timezone")
            _Timezone = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Timezone")
            OnTimezoneChanged()
        End Set
    End Property

    Private _Timezone As Nullable(Of Global.System.Int32)
    Private Partial Sub OnTimezoneChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnTimezoneChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property State() As Global.System.String
        Get
            Return _State
        End Get
        Set
            OnStateChanging(value)
            ReportPropertyChanging("State")
            _State = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("State")
            OnStateChanged()
        End Set
    End Property

    Private _State As Global.System.String
    Private Partial Sub OnStateChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnStateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property StateAbbr() As Global.System.String
        Get
            Return _StateAbbr
        End Get
        Set
            OnStateAbbrChanging(value)
            ReportPropertyChanging("StateAbbr")
            _StateAbbr = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("StateAbbr")
            OnStateAbbrChanged()
        End Set
    End Property

    Private _StateAbbr As Global.System.String
    Private Partial Sub OnStateAbbrChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnStateAbbrChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ICOMSModel", "FK_Franchise_UPS_DivisionLookups_UPS", "DivisionLookups_UPS")>
    Public Property DivisionLookups_UPS() As DivisionLookups_UPS
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of DivisionLookups_UPS)("ICOMSModel.FK_Franchise_UPS_DivisionLookups_UPS", "DivisionLookups_UPS").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of DivisionLookups_UPS)("ICOMSModel.FK_Franchise_UPS_DivisionLookups_UPS", "DivisionLookups_UPS").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property DivisionLookups_UPSReference() As EntityReference(Of DivisionLookups_UPS)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of DivisionLookups_UPS)("ICOMSModel.FK_Franchise_UPS_DivisionLookups_UPS", "DivisionLookups_UPS")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of DivisionLookups_UPS)("ICOMSModel.FK_Franchise_UPS_DivisionLookups_UPS", "DivisionLookups_UPS", value)
            End If
        End Set
    End Property

    #End Region

End Class

#End Region


