'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports NetSqlAzMan.Interfaces
Imports System
Imports System.Collections.Generic

'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated by NetSqlAzMan CodeDom.
'    NetSqlAzMan - Andrea Ferendeles - http://netsqlazman.codeplex.com
'    NetSqlAzMan Version: 3.6.0.8
'    CLR Version: v4.0.30319
'    <NetSqlAzMan-info>
'       Store: CCCWEB
'       Application: GeneralForms
'       Last update: 3/4/2011 1:21:14 PM
'    </NetSqlAzMan-info>
' </auto-generated>
'------------------------------------------------------------------------------
'
'
'TODO: Add NetSqlAzMan.dll Assembly reference.
'
'
Namespace Security
    '''<summary>
    '''NetSqlAzMan Check Access Helper Class for NetSqlAzMan 'GeneralForms' Application 
    '''</summary>
    Partial Public Class CheckAccessHelper
#Region "Constants"
        '''<summary>
        '''Store Name
        '''</summary>
        Protected Friend Const STORE_NAME As String = "CCCWEB"
        '''<summary>
        '''Application Name
        '''</summary>
        Protected Friend Const APPLICATION_NAME As String = "GeneralForms"
#End Region
#Region "Fields"
        '''<summary>
        '''NetSqlAzMan Storage reference.
        '''</summary>
        Protected mStorage As NetSqlAzMan.Interfaces.IAzManStorage
        '''<summary>
        '''User Windows Principal Identity.
        '''</summary>
        Protected windowsIdentity As System.Security.Principal.WindowsIdentity
#End Region
#Region "Constructors"
        '''<summary>
        '''Initializes a new instance of the <see cref="T:CheckAccessHelper"/> class [Windows Users ONLY].
        '''</summary>
        '''<param name="storageConnectionString">The storage connection string.</param>
        '''<param name="windowsIdentity">The Windows Principal Identity.</param>
        Public Sub New(ByVal storageConnectionString As String, ByVal windowsIdentity As System.Security.Principal.WindowsIdentity)
            MyBase.New()
            Me.mStorage = New NetSqlAzMan.SqlAzManStorage(storageConnectionString)
            Me.windowsIdentity = windowsIdentity
        End Sub
        '''<summary>
        '''Initializes a new instance of the <see cref="T:CheckAccessHelper"/> class [DB Users ONLY].
        '''</summary>
        '''<param name="storageConnectionString">The storage connection string.</param>
        Public Sub New(ByVal storageConnectionString As String)
            MyBase.New()
            Me.mStorage = New NetSqlAzMan.SqlAzManStorage(storageConnectionString)
        End Sub
#End Region
#Region "Properties"
        '''<summary>
        '''Gets the NetSqlAzMan Storage.
        '''</summary>
        Public Overridable ReadOnly Property Storage() As NetSqlAzMan.Interfaces.IAzManStorage
            Get
                Return Me.mStorage
            End Get
        End Property
#End Region
#Region "Methods"
        '''<summary>
        '''Opens the connection
        '''</summary>
        Public Overridable Sub OpenConnection()
            Me.mStorage.OpenConnection()
        End Sub
        '''<summary>
        '''Closes the connection
        '''</summary>
        Public Overridable Sub CloseConnection()
            Me.mStorage.CloseConnection()
        End Sub
        '''<summary>
        '''Retrieve Item name from a Operation Enum.
        '''</summary>
        '''<param name="operation">The operation.</param>
        '''<returns>The Operation Name.</returns>
        Public Overridable Function ItemName(ByVal operation As Operation) As String
            If (operation = Operation.accessDirect) Then
                Return "accessDirect"
            End If
            Throw New System.ArgumentException("Unknown Operation name", "operation")
        End Function
        '''<summary>
        '''Checks the access [FOR Windows Users ONLY].
        '''</summary>
        '''<param name="itemName">The Item Name.</param>
        '''<param name="operationsOnly">if set to <c>true</c> checks the access for operations only.</param>
        '''<param name="contextParameters">Context Parameters for Biz Rules.</param>
        '''<returns>The Authorization Type [AllowWithDelegation, Allow, Deny, Neutral].</returns>
        Protected Overridable Overloads Function CheckAccess(ByVal itemName As String, ByVal operationsOnly As Boolean, <System.ParamArrayAttribute()> ByVal contextParameters As KeyValuePair(Of String, Object)()) As NetSqlAzMan.Interfaces.AuthorizationType
            Return Me.mStorage.CheckAccess(CheckAccessHelper.STORE_NAME, CheckAccessHelper.APPLICATION_NAME, itemName, Me.windowsIdentity, DateTime.Now, operationsOnly, contextParameters)
        End Function
        '''<summary>
        '''Checks the access [FOR DB Users ONLY].
        '''</summary>
        '''<param name="itemName">The Item Name.</param>
        '''<param name="dbUserName">The DB User Name.</param>
        '''<param name="operationsOnly">if set to <c>true</c> checks the access for operations only.</param>
        '''<param name="contextParameters">Context Parameters for Biz Rules.</param>
        '''<returns>The Authorization Type [AllowWithDelegation, Allow, Deny, Neutral].</returns>
        Protected Overridable Overloads Function CheckAccess(ByVal itemName As String, ByVal dbUserName As String, ByVal operationsOnly As Boolean, <System.ParamArrayAttribute()> ByVal contextParameters As KeyValuePair(Of String, Object)()) As NetSqlAzMan.Interfaces.AuthorizationType
            Return Me.mStorage.CheckAccess(CheckAccessHelper.STORE_NAME, CheckAccessHelper.APPLICATION_NAME, itemName, Me.mStorage.GetDBUser(dbUserName), DateTime.Now, operationsOnly, contextParameters)
        End Function
        '''<summary>
        '''Checks the access [FOR custom SID ONLY].
        '''</summary>
        '''<param name="itemName">The Item Name.</param>
        '''<param name="customSID">The custom SID.</param>
        '''<param name="operationsOnly">if set to <c>true</c> checks the access for operations only.</param>
        '''<param name="contextParameters">Context Parameters for Biz Rules.</param>
        '''<returns>The Authorization Type [AllowWithDelegation, Allow, Deny, Neutral].</returns>
        Protected Overridable Overloads Function CheckAccess(ByVal itemName As String, ByVal customSID As NetSqlAzMan.Interfaces.IAzManSid, ByVal operationsOnly As Boolean, <System.ParamArrayAttribute()> ByVal contextParameters As KeyValuePair(Of String, Object)()) As NetSqlAzMan.Interfaces.AuthorizationType
            Return Me.mStorage.CheckAccess(CheckAccessHelper.STORE_NAME, CheckAccessHelper.APPLICATION_NAME, itemName, Me.mStorage.GetDBUser(customSID), DateTime.Now, operationsOnly, contextParameters)
        End Function
        '''<summary>
        '''Checks the access [FOR Windows Users ONLY].
        '''</summary>
        '''<param name="itemName">The Item Name.</param>
        '''<param name="operationsOnly">if set to <c>true</c> checks the access for operations only.</param>
        '''<param name="contextParameters">Context Parameters for Biz Rules.</param>
        '''<param name="attributes">Retrieved attributes.</param>
        '''<returns>The Authorization Type [AllowWithDelegation, Allow, Deny, Neutral].</returns>
        Protected Overridable Overloads Function CheckAccess(ByVal itemName As String, ByVal operationsOnly As Boolean, ByRef attributes As System.Collections.Generic.List(Of System.Collections.Generic.KeyValuePair(Of String, String)), <System.ParamArrayAttribute()> ByVal contextParameters As KeyValuePair(Of String, Object)()) As NetSqlAzMan.Interfaces.AuthorizationType
            Return Me.mStorage.CheckAccess(CheckAccessHelper.STORE_NAME, CheckAccessHelper.APPLICATION_NAME, itemName, Me.windowsIdentity, DateTime.Now, operationsOnly, attributes, contextParameters)
        End Function
        '''<summary>
        '''Checks the access [FOR DB Users ONLY].
        '''</summary>
        '''<param name="itemName">The Item Name.</param>
        '''<param name="dbUserName">The DB User Name.</param>
        '''<param name="operationsOnly">if set to <c>true</c> checks the access for operations only.</param>
        '''<param name="attributes">Retrieved attributes.</param>
        '''<param name="contextParameters">Context Parameters for Biz Rules.</param>
        '''<returns>The Authorization Type [AllowWithDelegation, Allow, Deny, Neutral].</returns>
        Protected Overridable Overloads Function CheckAccess(ByVal itemName As String, ByVal dbUserName As String, ByVal operationsOnly As Boolean, ByRef attributes As System.Collections.Generic.List(Of System.Collections.Generic.KeyValuePair(Of String, String)), <System.ParamArrayAttribute()> ByVal contextParameters As KeyValuePair(Of String, Object)()) As NetSqlAzMan.Interfaces.AuthorizationType
            Return Me.mStorage.CheckAccess(CheckAccessHelper.STORE_NAME, CheckAccessHelper.APPLICATION_NAME, itemName, Me.mStorage.GetDBUser(dbUserName), DateTime.Now, operationsOnly, attributes, contextParameters)
        End Function
        '''<summary>
        '''Checks the access [FOR Custom SID ONLY].
        '''</summary>
        '''<param name="itemName">The Item Name.</param>
        '''<param name="customSID">The custom SID.</param>
        '''<param name="operationsOnly">if set to <c>true</c> checks the access for operations only.</param>
        '''<param name="attributes">Retrieved attributes.</param>
        '''<param name="contextParameters">Context Parameters for Biz Rules.</param>
        '''<returns>The Authorization Type [AllowWithDelegation, Allow, Deny, Neutral].</returns>
        Protected Overridable Overloads Function CheckAccess(ByVal itemName As String, ByVal customSID As NetSqlAzMan.Interfaces.IAzManSid, ByVal operationsOnly As Boolean, ByRef attributes As System.Collections.Generic.List(Of System.Collections.Generic.KeyValuePair(Of String, String)), <System.ParamArrayAttribute()> ByVal contextParameters As KeyValuePair(Of String, Object)()) As NetSqlAzMan.Interfaces.AuthorizationType
            Return Me.mStorage.CheckAccess(CheckAccessHelper.STORE_NAME, CheckAccessHelper.APPLICATION_NAME, itemName, Me.mStorage.GetDBUser(customSID), DateTime.Now, operationsOnly, attributes, contextParameters)
        End Function
        '''<summary>
        '''Gets the Authorization Type [FOR Windows Users ONLY].
        '''</summary>
        '''<param name="operation">The Operation.</param>
        '''<param name="contextParameters">Context Parameters for Biz Rules.</param>
        '''<returns>The Authorization Type [AllowWithDelegation, Allow, Deny, Neutral].</returns>
        Public Overridable Overloads Function GetAuthorizationType(ByVal operation As Operation, <System.ParamArrayAttribute()> ByVal contextParameters As KeyValuePair(Of String, Object)()) As NetSqlAzMan.Interfaces.AuthorizationType
            Return Me.CheckAccess(Me.ItemName(operation), True, contextParameters)
        End Function
        '''<summary>
        '''Gets the Authorization Type [FOR DB Users ONLY].
        '''</summary>
        '''<param name="operation">The Operation.</param>
        '''<param name="dbUserName">The DB UserName.</param>
        '''<param name="contextParameters">Context Parameters for Biz Rules.</param>
        '''<returns>The Authorization Type [AllowWithDelegation, Allow, Deny, Neutral].</returns>
        Public Overridable Overloads Function GetAuthorizationType(ByVal operation As Operation, ByVal dbUserName As String, <System.ParamArrayAttribute()> ByVal contextParameters As KeyValuePair(Of String, Object)()) As NetSqlAzMan.Interfaces.AuthorizationType
            Return Me.CheckAccess(Me.ItemName(operation), dbUserName, True, contextParameters)
        End Function
        '''<summary>
        '''Gets the Authorization Type [FOR Custom SID ONLY].
        '''</summary>
        '''<param name="operation">The Operation.</param>
        '''<param name="customSID">The Custom SID.</param>
        '''<param name="contextParameters">Context Parameters for Biz Rules.</param>
        '''<returns>The Authorization Type [AllowWithDelegation, Allow, Deny, Neutral].</returns>
        Public Overridable Overloads Function GetAuthorizationType(ByVal operation As Operation, ByVal customSID As NetSqlAzMan.Interfaces.IAzManSid, <System.ParamArrayAttribute()> ByVal contextParameters As KeyValuePair(Of String, Object)()) As NetSqlAzMan.Interfaces.AuthorizationType
            Return Me.CheckAccess(Me.ItemName(operation), customSID, True, contextParameters)
        End Function
        '''<summary>
        '''Gets the Authorization Type [FOR Windows Users ONLY].
        '''</summary>
        '''<param name="operation">The Operation.</param>
        '''<param name="attributes">Retrieved attributes.</param>
        '''<param name="contextParameters">Context Parameters for Biz Rules.</param>
        '''<returns>The Authorization Type [AllowWithDelegation, Allow, Deny, Neutral].</returns>
        Public Overridable Overloads Function GetAuthorizationType(ByVal operation As Operation, ByRef attributes As System.Collections.Generic.List(Of System.Collections.Generic.KeyValuePair(Of String, String)), <System.ParamArrayAttribute()> ByVal contextParameters As KeyValuePair(Of String, Object)()) As NetSqlAzMan.Interfaces.AuthorizationType
            Return Me.CheckAccess(Me.ItemName(operation), True, attributes, contextParameters)
        End Function
        '''<summary>
        '''Gets the Authorization Type [FOR DB Users ONLY].
        '''</summary>
        '''<param name="operation">The Operation.</param>
        '''<param name="dbUserName">The DB UserName.</param>
        '''<param name="attributes">Retrieved attributes.</param>
        '''<param name="contextParameters">Context Parameters for Biz Rules.</param>
        '''<returns>The Authorization Type [AllowWithDelegation, Allow, Deny, Neutral].</returns>
        Public Overridable Overloads Function GetAuthorizationType(ByVal operation As Operation, ByVal dbUserName As String, ByRef attributes As System.Collections.Generic.List(Of System.Collections.Generic.KeyValuePair(Of String, String)), <System.ParamArrayAttribute()> ByVal contextParameters As KeyValuePair(Of String, Object)()) As NetSqlAzMan.Interfaces.AuthorizationType
            Return Me.CheckAccess(Me.ItemName(operation), dbUserName, True, attributes, contextParameters)
        End Function
        '''<summary>
        '''Gets the Authorization Type [FOR custom SID ONLY].
        '''</summary>
        '''<param name="operation">The Operation.</param>
        '''<param name="customSID">The Custom SID.</param>
        '''<param name="attributes">Retrieved attributes.</param>
        '''<param name="contextParameters">Context Parameters for Biz Rules.</param>
        '''<returns>The Authorization Type [AllowWithDelegation, Allow, Deny, Neutral].</returns>
        Public Overridable Overloads Function GetAuthorizationType(ByVal operation As Operation, ByVal customSID As NetSqlAzMan.Interfaces.IAzManSid, ByRef attributes As System.Collections.Generic.List(Of System.Collections.Generic.KeyValuePair(Of String, String)), <System.ParamArrayAttribute()> ByVal contextParameters As KeyValuePair(Of String, Object)()) As NetSqlAzMan.Interfaces.AuthorizationType
            Return Me.CheckAccess(Me.ItemName(operation), customSID, True, attributes, contextParameters)
        End Function
        '''<summary>
        '''Checks the access [FOR Windows Users ONLY].
        '''</summary>
        '''<param name="operation">The Operation.</param>
        '''<param name="contextParameters">Context Parameters for Biz Rules.</param>
        '''<returns>True for Access Granted, False for Access Denied.</returns>
        Public Overridable Overloads Function CheckAccess(ByVal operation As Operation, <System.ParamArrayAttribute()> ByVal contextParameters As KeyValuePair(Of String, Object)()) As Boolean
            Dim result As NetSqlAzMan.Interfaces.AuthorizationType = Me.GetAuthorizationType(operation, contextParameters)
            Return ((result = AuthorizationType.AllowWithDelegation) _
                        OrElse (result = AuthorizationType.Allow))
        End Function
        '''<summary>
        '''Checks the access [FOR DB Users ONLY].
        '''</summary>
        '''<param name="operation">The Operation.</param>
        '''<param name="dbUserName">The DB UserName.</param>
        '''<param name="contextParameters">Context Parameters for Biz Rules.</param>
        '''<returns>True for Access Granted, False for Access Denied.</returns>
        Public Overridable Overloads Function CheckAccess(ByVal operation As Operation, ByVal dbUserName As String, <System.ParamArrayAttribute()> ByVal contextParameters As KeyValuePair(Of String, Object)()) As Boolean
            Dim result As NetSqlAzMan.Interfaces.AuthorizationType = Me.GetAuthorizationType(operation, dbUserName, contextParameters)
            Return ((result = AuthorizationType.AllowWithDelegation) _
                        OrElse (result = AuthorizationType.Allow))
        End Function
        '''<summary>
        '''Checks the access [FOR custom SID ONLY].
        '''</summary>
        '''<param name="operation">The Operation.</param>
        '''<param name="customSID">The custom SID.</param>
        '''<param name="contextParameters">Context Parameters for Biz Rules.</param>
        '''<returns>True for Access Granted, False for Access Denied.</returns>
        Public Overridable Overloads Function CheckAccess(ByVal operation As Operation, ByVal customSID As NetSqlAzMan.Interfaces.IAzManSid, <System.ParamArrayAttribute()> ByVal contextParameters As KeyValuePair(Of String, Object)()) As Boolean
            Dim result As NetSqlAzMan.Interfaces.AuthorizationType = Me.GetAuthorizationType(operation, customSID, contextParameters)
            Return ((result = AuthorizationType.AllowWithDelegation) _
                        OrElse (result = AuthorizationType.Allow))
        End Function
        '''<summary>
        '''Checks the access [FOR Windows Users ONLY].
        '''</summary>
        '''<param name="operation">The Operation.</param>
        '''<param name="attributes">Retrieved attributes.</param>
        '''<param name="contextParameters">Context Parameters for Biz Rules.</param>
        '''<returns>True for Access Granted, False for Access Denied.</returns>
        Public Overridable Overloads Function CheckAccess(ByVal operation As Operation, ByRef attributes As System.Collections.Generic.List(Of System.Collections.Generic.KeyValuePair(Of String, String)), <System.ParamArrayAttribute()> ByVal contextParameters As KeyValuePair(Of String, Object)()) As Boolean
            Dim result As NetSqlAzMan.Interfaces.AuthorizationType = Me.GetAuthorizationType(operation, attributes, contextParameters)
            Return ((result = AuthorizationType.AllowWithDelegation) _
                        OrElse (result = AuthorizationType.Allow))
        End Function
        '''<summary>
        '''Checks the access [FOR DB Users ONLY].
        '''</summary>
        '''<param name="operation">The Operation.</param>
        '''<param name="dbUserName">The DB UserName.</param>
        '''<param name="attributes">Retrieved attributes.</param>
        '''<param name="contextParameters">Context Parameters for Biz Rules.</param>
        '''<returns>True for Access Granted, False for Access Denied.</returns>
        Public Overridable Overloads Function CheckAccess(ByVal operation As Operation, ByVal dbUserName As String, ByRef attributes As System.Collections.Generic.List(Of System.Collections.Generic.KeyValuePair(Of String, String)), <System.ParamArrayAttribute()> ByVal contextParameters As KeyValuePair(Of String, Object)()) As Boolean
            Dim result As NetSqlAzMan.Interfaces.AuthorizationType = Me.GetAuthorizationType(operation, dbUserName, attributes, contextParameters)
            Return ((result = AuthorizationType.AllowWithDelegation) _
                        OrElse (result = AuthorizationType.Allow))
        End Function
        '''<summary>
        '''Checks the access [FOR custom SID ONLY].
        '''</summary>
        '''<param name="operation">The Operation.</param>
        '''<param name="customSID">The custom SID.</param>
        '''<param name="attributes">Retrieved attributes.</param>
        '''<param name="contextParameters">Context Parameters for Biz Rules.</param>
        '''<returns>True for Access Granted, False for Access Denied.</returns>
        Public Overridable Overloads Function CheckAccess(ByVal operation As Operation, ByVal customSID As NetSqlAzMan.Interfaces.IAzManSid, ByRef attributes As System.Collections.Generic.List(Of System.Collections.Generic.KeyValuePair(Of String, String)), <System.ParamArrayAttribute()> ByVal contextParameters As KeyValuePair(Of String, Object)()) As Boolean
            Dim result As NetSqlAzMan.Interfaces.AuthorizationType = Me.GetAuthorizationType(operation, customSID, attributes, contextParameters)
            Return ((result = AuthorizationType.AllowWithDelegation) _
                        OrElse (result = AuthorizationType.Allow))
        End Function
#End Region
#Region "Enums"
        '''<summary>
        '''Operations Enumeration
        '''</summary>
        Public Enum Operation
            '''<summary>
            '''Operation accessDirect
            '''</summary>
            accessDirect
        End Enum
#End Region
    End Class
End Namespace

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated by NetSqlAzMan CodeDom.
'    NetSqlAzMan - Andrea Ferendeles - http://netsqlazman.codeplex.com
'    NetSqlAzMan Version: 3.6.0.8
'    CLR Version: v4.0.30319
'    <NetSqlAzMan-info>
'       Store: CCCWEB
'       Application: GeneralForms
'       Last update: 3/4/2011 1:21:14 PM
'    </NetSqlAzMan-info>
' </auto-generated>
'------------------------------------------------------------------------------
'
Namespace Security
    '''<summary>
    '''NetSqlAzMan OPERATION Helper Class for NetSqlAzMan 'GeneralForms' Application 
    '''</summary>
    Partial Public Class OPERATION
        '''<summary>
        '''OPERATION 'accessDirect'
        '''</summary>
        Public Const ACCESSDIRECT As String = "accessDirect"
    End Class
End Namespace
