'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace OrderUpdateService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="OrderUpdateRequest", [Namespace]:="http://wowway.com/services/BillingSystem/OrderUpdate"),  _
     System.SerializableAttribute()>  _
    Partial Public Class OrderUpdateRequest
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ExternalUsernameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OccurrenceListField() As OrderUpdateService.Occurrence
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OrderNumberField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SiteIdField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ExternalUsername() As String
            Get
                Return Me.ExternalUsernameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ExternalUsernameField, value) <> true) Then
                    Me.ExternalUsernameField = value
                    Me.RaisePropertyChanged("ExternalUsername")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OccurrenceList() As OrderUpdateService.Occurrence()
            Get
                Return Me.OccurrenceListField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OccurrenceListField, value) <> true) Then
                    Me.OccurrenceListField = value
                    Me.RaisePropertyChanged("OccurrenceList")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OrderNumber() As String
            Get
                Return Me.OrderNumberField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OrderNumberField, value) <> true) Then
                    Me.OrderNumberField = value
                    Me.RaisePropertyChanged("OrderNumber")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SiteId() As String
            Get
                Return Me.SiteIdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SiteIdField, value) <> true) Then
                    Me.SiteIdField = value
                    Me.RaisePropertyChanged("SiteId")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Occurrence", [Namespace]:="http://schemas.datacontract.org/2004/07/WOW.BillingSystem.Contracts"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Occurrence
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ActionField As OrderUpdateService.BillingEnumAction
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OccurenceItemsField() As OrderUpdateService.ServiceItem
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OccurenceNumberField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OccurrenceTypeField As OrderUpdateService.BillingEnumOccurrenceType
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TNField As OrderUpdateService.TelephoneDetail
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Action() As OrderUpdateService.BillingEnumAction
            Get
                Return Me.ActionField
            End Get
            Set
                If (Me.ActionField.Equals(value) <> true) Then
                    Me.ActionField = value
                    Me.RaisePropertyChanged("Action")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OccurenceItems() As OrderUpdateService.ServiceItem()
            Get
                Return Me.OccurenceItemsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OccurenceItemsField, value) <> true) Then
                    Me.OccurenceItemsField = value
                    Me.RaisePropertyChanged("OccurenceItems")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OccurenceNumber() As Integer
            Get
                Return Me.OccurenceNumberField
            End Get
            Set
                If (Me.OccurenceNumberField.Equals(value) <> true) Then
                    Me.OccurenceNumberField = value
                    Me.RaisePropertyChanged("OccurenceNumber")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OccurrenceType() As OrderUpdateService.BillingEnumOccurrenceType
            Get
                Return Me.OccurrenceTypeField
            End Get
            Set
                If (Me.OccurrenceTypeField.Equals(value) <> true) Then
                    Me.OccurrenceTypeField = value
                    Me.RaisePropertyChanged("OccurrenceType")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TN() As OrderUpdateService.TelephoneDetail
            Get
                Return Me.TNField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TNField, value) <> true) Then
                    Me.TNField = value
                    Me.RaisePropertyChanged("TN")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="TelephoneDetail", [Namespace]:="http://schemas.datacontract.org/2004/07/WOW.BillingSystem.Contracts"),  _
     System.SerializableAttribute()>  _
    Partial Public Class TelephoneDetail
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ActionField As OrderUpdateService.BillingEnumAction
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AreaCodeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Block900976Field As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BlockCollectField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BlockInternationalField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BlockLongDistanceField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CSRNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DLField As OrderUpdateService.DirectoryListing
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ExchangeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FaxField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NumberField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PortedField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PrimaryField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SequenceField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Action() As OrderUpdateService.BillingEnumAction
            Get
                Return Me.ActionField
            End Get
            Set
                If (Me.ActionField.Equals(value) <> true) Then
                    Me.ActionField = value
                    Me.RaisePropertyChanged("Action")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AreaCode() As String
            Get
                Return Me.AreaCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AreaCodeField, value) <> true) Then
                    Me.AreaCodeField = value
                    Me.RaisePropertyChanged("AreaCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Block900976() As Boolean
            Get
                Return Me.Block900976Field
            End Get
            Set
                If (Me.Block900976Field.Equals(value) <> true) Then
                    Me.Block900976Field = value
                    Me.RaisePropertyChanged("Block900976")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BlockCollect() As Boolean
            Get
                Return Me.BlockCollectField
            End Get
            Set
                If (Me.BlockCollectField.Equals(value) <> true) Then
                    Me.BlockCollectField = value
                    Me.RaisePropertyChanged("BlockCollect")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BlockInternational() As Boolean
            Get
                Return Me.BlockInternationalField
            End Get
            Set
                If (Me.BlockInternationalField.Equals(value) <> true) Then
                    Me.BlockInternationalField = value
                    Me.RaisePropertyChanged("BlockInternational")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BlockLongDistance() As Boolean
            Get
                Return Me.BlockLongDistanceField
            End Get
            Set
                If (Me.BlockLongDistanceField.Equals(value) <> true) Then
                    Me.BlockLongDistanceField = value
                    Me.RaisePropertyChanged("BlockLongDistance")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CSRName() As String
            Get
                Return Me.CSRNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CSRNameField, value) <> true) Then
                    Me.CSRNameField = value
                    Me.RaisePropertyChanged("CSRName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DL() As OrderUpdateService.DirectoryListing
            Get
                Return Me.DLField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DLField, value) <> true) Then
                    Me.DLField = value
                    Me.RaisePropertyChanged("DL")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Exchange() As String
            Get
                Return Me.ExchangeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ExchangeField, value) <> true) Then
                    Me.ExchangeField = value
                    Me.RaisePropertyChanged("Exchange")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Fax() As Boolean
            Get
                Return Me.FaxField
            End Get
            Set
                If (Me.FaxField.Equals(value) <> true) Then
                    Me.FaxField = value
                    Me.RaisePropertyChanged("Fax")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Number() As String
            Get
                Return Me.NumberField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NumberField, value) <> true) Then
                    Me.NumberField = value
                    Me.RaisePropertyChanged("Number")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Ported() As Boolean
            Get
                Return Me.PortedField
            End Get
            Set
                If (Me.PortedField.Equals(value) <> true) Then
                    Me.PortedField = value
                    Me.RaisePropertyChanged("Ported")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Primary() As Boolean
            Get
                Return Me.PrimaryField
            End Get
            Set
                If (Me.PrimaryField.Equals(value) <> true) Then
                    Me.PrimaryField = value
                    Me.RaisePropertyChanged("Primary")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Sequence() As Integer
            Get
                Return Me.SequenceField
            End Get
            Set
                If (Me.SequenceField.Equals(value) <> true) Then
                    Me.SequenceField = value
                    Me.RaisePropertyChanged("Sequence")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="BillingEnum.Action", [Namespace]:="http://schemas.datacontract.org/2004/07/WOW.BillingSystem.Contracts")>  _
    Public Enum BillingEnumAction As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Add = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Remove = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Update = 3
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        None = 4
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        AutoAssign = 6
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ServiceItem", [Namespace]:="http://schemas.datacontract.org/2004/07/WOW.BillingSystem.Contracts"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ServiceItem
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ActionField As OrderUpdateService.BillingEnumAction
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private QuantityField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ServiceCodeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TotalQuantityField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private itemTypeField As OrderUpdateService.BillingEnumServiceCategory
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Action() As OrderUpdateService.BillingEnumAction
            Get
                Return Me.ActionField
            End Get
            Set
                If (Me.ActionField.Equals(value) <> true) Then
                    Me.ActionField = value
                    Me.RaisePropertyChanged("Action")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Quantity() As Integer
            Get
                Return Me.QuantityField
            End Get
            Set
                If (Me.QuantityField.Equals(value) <> true) Then
                    Me.QuantityField = value
                    Me.RaisePropertyChanged("Quantity")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ServiceCode() As String
            Get
                Return Me.ServiceCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ServiceCodeField, value) <> true) Then
                    Me.ServiceCodeField = value
                    Me.RaisePropertyChanged("ServiceCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TotalQuantity() As Integer
            Get
                Return Me.TotalQuantityField
            End Get
            Set
                If (Me.TotalQuantityField.Equals(value) <> true) Then
                    Me.TotalQuantityField = value
                    Me.RaisePropertyChanged("TotalQuantity")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property itemType() As OrderUpdateService.BillingEnumServiceCategory
            Get
                Return Me.itemTypeField
            End Get
            Set
                If (Me.itemTypeField.Equals(value) <> true) Then
                    Me.itemTypeField = value
                    Me.RaisePropertyChanged("itemType")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="BillingEnum.OccurrenceType", [Namespace]:="http://schemas.datacontract.org/2004/07/WOW.BillingSystem.Contracts")>  _
    Public Enum BillingEnumOccurrenceType As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Data = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Telephone = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Cable = 2
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="BillingEnum.ServiceCategory", [Namespace]:="http://schemas.datacontract.org/2004/07/WOW.BillingSystem.Contracts")>  _
    Public Enum BillingEnumServiceCategory As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Data = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Telephone = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Cable = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        OTC = 3
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DirectoryListing", [Namespace]:="http://schemas.datacontract.org/2004/07/WOW.BillingSystem.Contracts"),  _
     System.SerializableAttribute()>  _
    Partial Public Class DirectoryListing
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DLInstructionsField As OrderUpdateService.BillingEnumListingInstruction
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FirstNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LastNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SuffixField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TitleField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DLInstructions() As OrderUpdateService.BillingEnumListingInstruction
            Get
                Return Me.DLInstructionsField
            End Get
            Set
                If (Me.DLInstructionsField.Equals(value) <> true) Then
                    Me.DLInstructionsField = value
                    Me.RaisePropertyChanged("DLInstructions")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FirstName() As String
            Get
                Return Me.FirstNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FirstNameField, value) <> true) Then
                    Me.FirstNameField = value
                    Me.RaisePropertyChanged("FirstName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property LastName() As String
            Get
                Return Me.LastNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LastNameField, value) <> true) Then
                    Me.LastNameField = value
                    Me.RaisePropertyChanged("LastName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Suffix() As String
            Get
                Return Me.SuffixField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SuffixField, value) <> true) Then
                    Me.SuffixField = value
                    Me.RaisePropertyChanged("Suffix")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Title() As String
            Get
                Return Me.TitleField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TitleField, value) <> true) Then
                    Me.TitleField = value
                    Me.RaisePropertyChanged("Title")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="BillingEnum.ListingInstruction", [Namespace]:="http://schemas.datacontract.org/2004/07/WOW.BillingSystem.Contracts")>  _
    Public Enum BillingEnumListingInstruction As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Listed = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        NonListed = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        NonPublished = 2
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ValidationException", [Namespace]:="http://wowway.com/services/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ValidationException
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CustomMessageField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CustomMessage() As String
            Get
                Return Me.CustomMessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CustomMessageField, value) <> true) Then
                    Me.CustomMessageField = value
                    Me.RaisePropertyChanged("CustomMessage")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="BillingSystemException", [Namespace]:="http://wowway.com/services/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class BillingSystemException
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CustomMessageField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CustomMessage() As String
            Get
                Return Me.CustomMessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CustomMessageField, value) <> true) Then
                    Me.CustomMessageField = value
                    Me.RaisePropertyChanged("CustomMessage")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ScheduleRequest", [Namespace]:="http://wowway.com/services/BillingSystem/OrderUpdate"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ScheduleRequest
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ExternalPasswordField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ExternalUsernameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OrderNumberField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ReasonCodeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ScheduleDateField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SiteIdField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TimeSlotField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ExternalPassword() As String
            Get
                Return Me.ExternalPasswordField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ExternalPasswordField, value) <> true) Then
                    Me.ExternalPasswordField = value
                    Me.RaisePropertyChanged("ExternalPassword")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ExternalUsername() As String
            Get
                Return Me.ExternalUsernameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ExternalUsernameField, value) <> true) Then
                    Me.ExternalUsernameField = value
                    Me.RaisePropertyChanged("ExternalUsername")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OrderNumber() As String
            Get
                Return Me.OrderNumberField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OrderNumberField, value) <> true) Then
                    Me.OrderNumberField = value
                    Me.RaisePropertyChanged("OrderNumber")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ReasonCode() As String
            Get
                Return Me.ReasonCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ReasonCodeField, value) <> true) Then
                    Me.ReasonCodeField = value
                    Me.RaisePropertyChanged("ReasonCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ScheduleDate() As String
            Get
                Return Me.ScheduleDateField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ScheduleDateField, value) <> true) Then
                    Me.ScheduleDateField = value
                    Me.RaisePropertyChanged("ScheduleDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SiteId() As String
            Get
                Return Me.SiteIdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SiteIdField, value) <> true) Then
                    Me.SiteIdField = value
                    Me.RaisePropertyChanged("SiteId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TimeSlot() As String
            Get
                Return Me.TimeSlotField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TimeSlotField, value) <> true) Then
                    Me.TimeSlotField = value
                    Me.RaisePropertyChanged("TimeSlot")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="UnlockRequest", [Namespace]:="http://wowway.com/services/BillingSystem/OrderUpdate"),  _
     System.SerializableAttribute()>  _
    Partial Public Class UnlockRequest
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ExternalUsernameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OrderNumberField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SiteIdField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ExternalUsername() As String
            Get
                Return Me.ExternalUsernameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ExternalUsernameField, value) <> true) Then
                    Me.ExternalUsernameField = value
                    Me.RaisePropertyChanged("ExternalUsername")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OrderNumber() As String
            Get
                Return Me.OrderNumberField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OrderNumberField, value) <> true) Then
                    Me.OrderNumberField = value
                    Me.RaisePropertyChanged("OrderNumber")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SiteId() As String
            Get
                Return Me.SiteIdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SiteIdField, value) <> true) Then
                    Me.SiteIdField = value
                    Me.RaisePropertyChanged("SiteId")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://wowway.com/services/BillingSystem/OrderUpdate", ConfigurationName:="OrderUpdateService.IOrderUpdate")>  _
    Public Interface IOrderUpdate
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://wowway.com/services/BillingSystem/OrderUpdate/IOrderUpdate/AddServiceCode", ReplyAction:="http://wowway.com/services/BillingSystem/OrderUpdate/IOrderUpdate/AddServiceCodeR"& _ 
            "esponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(OrderUpdateService.ValidationException), Action:="http://wowway.com/services/BillingSystem/OrderUpdate/IOrderUpdate/AddServiceCodeV"& _ 
            "alidationExceptionFault", Name:="ValidationException", [Namespace]:="http://wowway.com/services/"),  _
         System.ServiceModel.FaultContractAttribute(GetType(OrderUpdateService.BillingSystemException), Action:="http://wowway.com/services/BillingSystem/OrderUpdate/IOrderUpdate/AddServiceCodeB"& _ 
            "illingSystemExceptionFault", Name:="BillingSystemException", [Namespace]:="http://wowway.com/services/")>  _
        Sub AddServiceCode(ByVal request As OrderUpdateService.OrderUpdateRequest)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://wowway.com/services/BillingSystem/OrderUpdate/IOrderUpdate/Schedule", ReplyAction:="http://wowway.com/services/BillingSystem/OrderUpdate/IOrderUpdate/ScheduleRespons"& _ 
            "e"),  _
         System.ServiceModel.FaultContractAttribute(GetType(OrderUpdateService.ValidationException), Action:="http://wowway.com/services/BillingSystem/OrderUpdate/IOrderUpdate/ScheduleValidat"& _ 
            "ionExceptionFault", Name:="ValidationException", [Namespace]:="http://wowway.com/services/"),  _
         System.ServiceModel.FaultContractAttribute(GetType(OrderUpdateService.BillingSystemException), Action:="http://wowway.com/services/BillingSystem/OrderUpdate/IOrderUpdate/ScheduleBilling"& _ 
            "SystemExceptionFault", Name:="BillingSystemException", [Namespace]:="http://wowway.com/services/")>  _
        Sub Schedule(ByVal request As OrderUpdateService.ScheduleRequest)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://wowway.com/services/BillingSystem/OrderUpdate/IOrderUpdate/Unlock", ReplyAction:="http://wowway.com/services/BillingSystem/OrderUpdate/IOrderUpdate/UnlockResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(OrderUpdateService.ValidationException), Action:="http://wowway.com/services/BillingSystem/OrderUpdate/IOrderUpdate/UnlockValidatio"& _ 
            "nExceptionFault", Name:="ValidationException", [Namespace]:="http://wowway.com/services/"),  _
         System.ServiceModel.FaultContractAttribute(GetType(OrderUpdateService.BillingSystemException), Action:="http://wowway.com/services/BillingSystem/OrderUpdate/IOrderUpdate/UnlockBillingSy"& _ 
            "stemExceptionFault", Name:="BillingSystemException", [Namespace]:="http://wowway.com/services/")>  _
        Sub Unlock(ByVal request As OrderUpdateService.UnlockRequest)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IOrderUpdateChannel
        Inherits OrderUpdateService.IOrderUpdate, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class OrderUpdateClient
        Inherits System.ServiceModel.ClientBase(Of OrderUpdateService.IOrderUpdate)
        Implements OrderUpdateService.IOrderUpdate
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Sub AddServiceCode(ByVal request As OrderUpdateService.OrderUpdateRequest) Implements OrderUpdateService.IOrderUpdate.AddServiceCode
            MyBase.Channel.AddServiceCode(request)
        End Sub
        
        Public Sub Schedule(ByVal request As OrderUpdateService.ScheduleRequest) Implements OrderUpdateService.IOrderUpdate.Schedule
            MyBase.Channel.Schedule(request)
        End Sub
        
        Public Sub Unlock(ByVal request As OrderUpdateService.UnlockRequest) Implements OrderUpdateService.IOrderUpdate.Unlock
            MyBase.Channel.Unlock(request)
        End Sub
    End Class
End Namespace
