'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace CustomerService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Cust", [Namespace]:="http://schemas.datacontract.org/2004/07/Customer"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Cust
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AddressField As CustomerService.AddressIcoms
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FullNameFirstLastField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FullNameLastFirstField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IcomsCustomerIDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PrimaryPhoneField As CustomerService.PhoneNumber
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSNField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SecondaryPhoneField As CustomerService.PhoneNumber
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Address() As CustomerService.AddressIcoms
            Get
                Return Me.AddressField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AddressField, value) <> true) Then
                    Me.AddressField = value
                    Me.RaisePropertyChanged("Address")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FName() As String
            Get
                Return Me.FNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FNameField, value) <> true) Then
                    Me.FNameField = value
                    Me.RaisePropertyChanged("FName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FullNameFirstLast() As String
            Get
                Return Me.FullNameFirstLastField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FullNameFirstLastField, value) <> true) Then
                    Me.FullNameFirstLastField = value
                    Me.RaisePropertyChanged("FullNameFirstLast")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FullNameLastFirst() As String
            Get
                Return Me.FullNameLastFirstField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FullNameLastFirstField, value) <> true) Then
                    Me.FullNameLastFirstField = value
                    Me.RaisePropertyChanged("FullNameLastFirst")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IcomsCustomerID() As String
            Get
                Return Me.IcomsCustomerIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IcomsCustomerIDField, value) <> true) Then
                    Me.IcomsCustomerIDField = value
                    Me.RaisePropertyChanged("IcomsCustomerID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property LName() As String
            Get
                Return Me.LNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LNameField, value) <> true) Then
                    Me.LNameField = value
                    Me.RaisePropertyChanged("LName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PrimaryPhone() As CustomerService.PhoneNumber
            Get
                Return Me.PrimaryPhoneField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PrimaryPhoneField, value) <> true) Then
                    Me.PrimaryPhoneField = value
                    Me.RaisePropertyChanged("PrimaryPhone")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SSN() As String
            Get
                Return Me.SSNField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSNField, value) <> true) Then
                    Me.SSNField = value
                    Me.RaisePropertyChanged("SSN")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SecondaryPhone() As CustomerService.PhoneNumber
            Get
                Return Me.SecondaryPhoneField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SecondaryPhoneField, value) <> true) Then
                    Me.SecondaryPhoneField = value
                    Me.RaisePropertyChanged("SecondaryPhone")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="AddressIcoms", [Namespace]:="http://schemas.datacontract.org/2004/07/Address"),  _
     System.SerializableAttribute()>  _
    Partial Public Class AddressIcoms
        Inherits CustomerService.AddressBase
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CompanyField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DivisionField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FranchiseField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FranchiseNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IcomsLocationIDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LegacyPrinField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PoolField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ValidField As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Company() As Integer
            Get
                Return Me.CompanyField
            End Get
            Set
                If (Me.CompanyField.Equals(value) <> true) Then
                    Me.CompanyField = value
                    Me.RaisePropertyChanged("Company")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Division() As Integer
            Get
                Return Me.DivisionField
            End Get
            Set
                If (Me.DivisionField.Equals(value) <> true) Then
                    Me.DivisionField = value
                    Me.RaisePropertyChanged("Division")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Franchise() As Integer
            Get
                Return Me.FranchiseField
            End Get
            Set
                If (Me.FranchiseField.Equals(value) <> true) Then
                    Me.FranchiseField = value
                    Me.RaisePropertyChanged("Franchise")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FranchiseName() As String
            Get
                Return Me.FranchiseNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FranchiseNameField, value) <> true) Then
                    Me.FranchiseNameField = value
                    Me.RaisePropertyChanged("FranchiseName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IcomsLocationID() As String
            Get
                Return Me.IcomsLocationIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IcomsLocationIDField, value) <> true) Then
                    Me.IcomsLocationIDField = value
                    Me.RaisePropertyChanged("IcomsLocationID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property LegacyPrin() As String
            Get
                Return Me.LegacyPrinField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LegacyPrinField, value) <> true) Then
                    Me.LegacyPrinField = value
                    Me.RaisePropertyChanged("LegacyPrin")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Pool() As String
            Get
                Return Me.PoolField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PoolField, value) <> true) Then
                    Me.PoolField = value
                    Me.RaisePropertyChanged("Pool")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Valid() As Boolean
            Get
                Return Me.ValidField
            End Get
            Set
                If (Me.ValidField.Equals(value) <> true) Then
                    Me.ValidField = value
                    Me.RaisePropertyChanged("Valid")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="PhoneNumber", [Namespace]:="http://schemas.datacontract.org/2004/07/Customer"),  _
     System.SerializableAttribute()>  _
    Partial Public Class PhoneNumber
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AreaCodeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FormattedPhoneField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PhoneOnlyField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RegionField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AreaCode() As String
            Get
                Return Me.AreaCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AreaCodeField, value) <> true) Then
                    Me.AreaCodeField = value
                    Me.RaisePropertyChanged("AreaCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FormattedPhone() As String
            Get
                Return Me.FormattedPhoneField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FormattedPhoneField, value) <> true) Then
                    Me.FormattedPhoneField = value
                    Me.RaisePropertyChanged("FormattedPhone")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PhoneOnly() As String
            Get
                Return Me.PhoneOnlyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PhoneOnlyField, value) <> true) Then
                    Me.PhoneOnlyField = value
                    Me.RaisePropertyChanged("PhoneOnly")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Region() As String
            Get
                Return Me.RegionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RegionField, value) <> true) Then
                    Me.RegionField = value
                    Me.RaisePropertyChanged("Region")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="AddressBase", [Namespace]:="http://schemas.datacontract.org/2004/07/Address"),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(CustomerService.AddressValidateOutput)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(CustomerService.AddressIcoms))>  _
    Partial Public Class AddressBase
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Addr1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Addr2Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CityField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FormattedAddressField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private HouseNumberField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StateField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StreetNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ZipField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Zip4Field As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Addr1() As String
            Get
                Return Me.Addr1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Addr1Field, value) <> true) Then
                    Me.Addr1Field = value
                    Me.RaisePropertyChanged("Addr1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Addr2() As String
            Get
                Return Me.Addr2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Addr2Field, value) <> true) Then
                    Me.Addr2Field = value
                    Me.RaisePropertyChanged("Addr2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property City() As String
            Get
                Return Me.CityField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CityField, value) <> true) Then
                    Me.CityField = value
                    Me.RaisePropertyChanged("City")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FormattedAddress() As String
            Get
                Return Me.FormattedAddressField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FormattedAddressField, value) <> true) Then
                    Me.FormattedAddressField = value
                    Me.RaisePropertyChanged("FormattedAddress")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property HouseNumber() As String
            Get
                Return Me.HouseNumberField
            End Get
            Set
                If (Object.ReferenceEquals(Me.HouseNumberField, value) <> true) Then
                    Me.HouseNumberField = value
                    Me.RaisePropertyChanged("HouseNumber")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property State() As String
            Get
                Return Me.StateField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StateField, value) <> true) Then
                    Me.StateField = value
                    Me.RaisePropertyChanged("State")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StreetName() As String
            Get
                Return Me.StreetNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StreetNameField, value) <> true) Then
                    Me.StreetNameField = value
                    Me.RaisePropertyChanged("StreetName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Zip() As String
            Get
                Return Me.ZipField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ZipField, value) <> true) Then
                    Me.ZipField = value
                    Me.RaisePropertyChanged("Zip")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Zip4() As String
            Get
                Return Me.Zip4Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Zip4Field, value) <> true) Then
                    Me.Zip4Field = value
                    Me.RaisePropertyChanged("Zip4")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="AddressValidateOutput", [Namespace]:="http://schemas.datacontract.org/2004/07/Address"),  _
     System.SerializableAttribute()>  _
    Partial Public Class AddressValidateOutput
        Inherits CustomerService.AddressBase
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AddressConfirmedField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DuoShareMessageField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FriendlyResultMessageField As String
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AddressConfirmed() As Boolean
            Get
                Return Me.AddressConfirmedField
            End Get
            Set
                If (Me.AddressConfirmedField.Equals(value) <> true) Then
                    Me.AddressConfirmedField = value
                    Me.RaisePropertyChanged("AddressConfirmed")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DuoShareMessage() As String
            Get
                Return Me.DuoShareMessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DuoShareMessageField, value) <> true) Then
                    Me.DuoShareMessageField = value
                    Me.RaisePropertyChanged("DuoShareMessage")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FriendlyResultMessage() As String
            Get
                Return Me.FriendlyResultMessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FriendlyResultMessageField, value) <> true) Then
                    Me.FriendlyResultMessageField = value
                    Me.RaisePropertyChanged("FriendlyResultMessage")
                End If
            End Set
        End Property
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="CustomerService.ICustomerManagement")>  _
    Public Interface ICustomerManagement
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICustomerManagement/getByCustomerID", ReplyAction:="http://tempuri.org/ICustomerManagement/getByCustomerIDResponse")>  _
        Function getByCustomerID(ByVal custID As String) As CustomerService.Cust
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICustomerManagement/getByPhoneNumber", ReplyAction:="http://tempuri.org/ICustomerManagement/getByPhoneNumberResponse")>  _
        Function getByPhoneNumber(ByVal phoneNumber As String) As CustomerService.Cust
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICustomerManagement/getByName", ReplyAction:="http://tempuri.org/ICustomerManagement/getByNameResponse")>  _
        Function getByName(ByVal LastName As String, ByVal FirstName As String) As CustomerService.Cust
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ICustomerManagementChannel
        Inherits CustomerService.ICustomerManagement, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class CustomerManagementClient
        Inherits System.ServiceModel.ClientBase(Of CustomerService.ICustomerManagement)
        Implements CustomerService.ICustomerManagement
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function getByCustomerID(ByVal custID As String) As CustomerService.Cust Implements CustomerService.ICustomerManagement.getByCustomerID
            Return MyBase.Channel.getByCustomerID(custID)
        End Function
        
        Public Function getByPhoneNumber(ByVal phoneNumber As String) As CustomerService.Cust Implements CustomerService.ICustomerManagement.getByPhoneNumber
            Return MyBase.Channel.getByPhoneNumber(phoneNumber)
        End Function
        
        Public Function getByName(ByVal LastName As String, ByVal FirstName As String) As CustomerService.Cust Implements CustomerService.ICustomerManagement.getByName
            Return MyBase.Channel.getByName(LastName, FirstName)
        End Function
    End Class
End Namespace
